package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.exception.RateLimitExceededException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentHashMap.KeySetView;
import java.util.concurrent.CancellationException;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 *
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {

    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final int MAX_CONTEXT_SNIPPET_LEN = 300;
    private static final int MAX_MATCHED_CHUNK_LEN = 800;
    private static final int MAX_EVIDENCE_SNIPPET_LEN = 160;
    private static final int GENERATION_COMPLETION_TIMEOUT_SECONDS = 120;
    private static final int MAX_REACT_ROUNDS = 4;
    private static final int MAX_REACT_TOOL_CALLS = 8;
    private static final int REACT_MAX_COMPLETION_TOKENS = 2000;
    private static final int INITIAL_SEARCH_PAGE_BATCH_SIZE = 5;
    private static final String INITIAL_SEARCH_TOOL_CALL_ID = "initial-search";
    private static final String SMALLTALK_RESPONSE = "我在。你可以直接问论文的方法、实验、结论、表格或某个引用点。";
    private static final Pattern CITED_REFERENCE_PATTERN =
            Pattern.compile("\\[(\\d+)]");
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final PaperRetrievalService paperRetrievalService;
    private final PaperAnswerService paperAnswerService;
    private final LlmProviderRouter llmProviderRouter;
    private final RateLimitService rateLimitService;
    private final ConversationService conversationService;
    private final ChatGenerationStateService chatGenerationStateService;
    private final ChatSessionRegistry chatSessionRegistry;
    private final AgentToolRegistry agentToolRegistry;
    private final ThreadPoolTaskExecutor chatMonitorExecutor;
    private final ObjectMapper objectMapper;

    // 用于存储每次生成任务的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每次生成任务的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 用于持有正在进行中的 LLM 流，支持主动取消上游请求
    private final Map<String, LlmProviderRouter.StreamHandle> activeStreams = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于标记已经取消的生成任务，防止后续又被落成 completed
    private final KeySetView<String, Boolean> cancelledGenerations = ConcurrentHashMap.newKeySet();
    // 记录每次生成任务归属的前端页面实例，避免同一用户多个标签页之间串流。
    private final Map<String, String> generationClientIds = new ConcurrentHashMap<>();
    // 用于存储每次生成任务的引用映射：generationId -> {referenceNumber -> detail}
    private final Map<String, Map<Integer, ReferenceInfo>> generationReferenceMappings = new ConcurrentHashMap<>();
    private final Map<String, Map<String, Object>> generationDiagnostics = new ConcurrentHashMap<>();
    private final Map<String, ChatRequestTiming> generationTimings = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      PaperRetrievalService paperRetrievalService,
                      PaperAnswerService paperAnswerService,
                      LlmProviderRouter llmProviderRouter,
                      RateLimitService rateLimitService,
                      ConversationService conversationService,
                      ChatGenerationStateService chatGenerationStateService,
                      ChatSessionRegistry chatSessionRegistry,
                      AgentToolRegistry agentToolRegistry,
                      ObjectMapper objectMapper,
                      @Qualifier("chatMonitorExecutor") ThreadPoolTaskExecutor chatMonitorExecutor) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.paperRetrievalService = paperRetrievalService;
        this.paperAnswerService = paperAnswerService;
        this.llmProviderRouter = llmProviderRouter;
        this.rateLimitService = rateLimitService;
        this.conversationService = conversationService;
        this.chatGenerationStateService = chatGenerationStateService;
        this.chatSessionRegistry = chatSessionRegistry;
        this.agentToolRegistry = agentToolRegistry;
        this.objectMapper = objectMapper;
        this.chatMonitorExecutor = chatMonitorExecutor;
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        processMessage(userId, new ChatRequest(userMessage, null), session);
    }

    public void processMessage(String userId, ChatRequest request, WebSocketSession session) {
        String userMessage = request == null ? "" : request.message();
        PaperAnswerService.AnswerScope scope = request == null ? null : request.scope();
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        String requestClientId = resolveClientId(session);
        String conversationId = null;
        String generationId = null;
        try {
            rateLimitService.checkChatByUser(userId);

            // 1. 获取或创建会话 ID
            conversationId = getOrCreateConversationId(userId);
            conversationService.ensureConversationSession(Long.parseLong(userId), conversationId, userMessage);
            ChatGenerationStateService.GenerationSnapshot generation =
                    chatGenerationStateService.createGeneration(userId, conversationId, userMessage);
            generationId = generation.generationId();
            final String finalConversationId = conversationId;
            final String finalGenerationId = generationId;
            generationClientIds.put(finalGenerationId, requestClientId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            sendGenerationStart(userId, finalGenerationId, finalConversationId);
            ChatRequestTiming timing = ChatRequestTiming.start(userMessage);
            generationTimings.put(finalGenerationId, timing);

            // 为当前生成任务创建响应构建器
            responseBuilders.put(finalGenerationId, new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(finalGenerationId, responseFuture);

            if (isSmalltalkMessage(userMessage)) {
                timing.route("SMALLTALK");
                timing.mark("intent_route_decided");
                completeSmalltalkResponse(userId, userMessage, finalConversationId, finalGenerationId, responseFuture);
                return;
            }
            timing.route("PAPER_QA");
            timing.mark("intent_route_decided");

            // 2. 异步执行 Evidence Harness；默认用户聊天不再让模型自由调度工具和 citation。
            try {
                chatMonitorExecutor.execute(() ->
                        runEvidenceHarnessSafely(userId, userMessage, finalConversationId, finalGenerationId, scope, responseFuture));
            } catch (RejectedExecutionException ex) {
                logger.warn("聊天处理线程池已满，generationId: {}", finalGenerationId);
                RuntimeException busyException = new RuntimeException("系统繁忙，请稍后重试");
                chatGenerationStateService.markFailed(finalGenerationId, busyException.getMessage());
                handleError(userId, requestClientId, finalGenerationId, busyException);
                sendCompletionNotification(userId, finalGenerationId, finalConversationId, true, false);
                cleanupGenerationState(finalGenerationId, ex);
            }

        } catch (RateLimitExceededException e) {
            sendRateLimitMessage(userId, requestClientId, null, e);
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            if (generationId != null) {
                chatGenerationStateService.markFailed(generationId, e.getMessage());
                cleanupGenerationState(generationId, e);
            }
            handleError(userId, requestClientId, generationId, e);
        }
    }

    private void runReActLoopSafely(String userId,
                                    String userMessage,
                                    String conversationId,
                                    String generationId,
                                    List<Map<String, String>> history,
                                    CompletableFuture<String> responseFuture) {
        try {
            runReActLoop(userId, userMessage, conversationId, generationId, history, responseFuture);
        } catch (Exception e) {
            logger.error("ReAct 循环执行失败: generationId={}", generationId, e);
            chatGenerationStateService.markFailed(generationId, e.getMessage());
            handleError(userId, generationId, e);
            sendCompletionNotification(userId, generationId, conversationId, true, false);
            cleanupGenerationState(generationId, e);
        }
    }

    private void completeSmalltalkResponse(String userId,
                                           String userMessage,
                                           String conversationId,
                                           String generationId,
                                           CompletableFuture<String> responseFuture) {
        appendStreamChunk(userId, generationId, conversationId, SMALLTALK_RESPONSE);
        finalizeResponse(
                userId,
                userMessage,
                conversationId,
                generationId,
                responseFuture,
                responseBuilders.get(generationId),
                new LlmProviderRouter.StreamCompletion("smalltalk", 0, 0, SMALLTALK_RESPONSE.length())
        );
    }

    private void runEvidenceHarnessSafely(String userId,
                                          String userMessage,
                                          String conversationId,
                                          String generationId,
                                          PaperAnswerService.AnswerScope scope,
                                          CompletableFuture<String> responseFuture) {
        try {
            runEvidenceHarness(userId, userMessage, conversationId, generationId, scope, responseFuture);
        } catch (Exception e) {
            logger.error("Evidence Harness 执行失败: generationId={}", generationId, e);
            chatGenerationStateService.markFailed(generationId, e.getMessage());
            handleError(userId, generationId, e);
            sendCompletionNotification(userId, generationId, conversationId, true, false);
            cleanupGenerationState(generationId, e);
        }
    }

    private void runEvidenceHarness(String userId,
                                    String userMessage,
                                    String conversationId,
                                    String generationId,
                                    PaperAnswerService.AnswerScope scope,
                                    CompletableFuture<String> responseFuture) {
        ChatRequestTiming timing = generationTimings.get(generationId);
        if (timing != null) {
            timing.begin("harness");
        }
        PaperAnswerService.AnswerResult answer = paperAnswerService.answer(userId, conversationId, userMessage, scope);
        if (timing != null) {
            timing.end("harness");
            timing.route(answer.intent().name());
            timing.retrievalHitCount(answer.evidenceCount());
        }
        if (!answer.referenceMappings().isEmpty()) {
            generationReferenceMappings.put(generationId, answer.referenceMappings());
            chatGenerationStateService.updateReferenceMappings(generationId, toSerializableReferenceMappings(answer.referenceMappings()));
        }
        Map<String, Object> diagnostics = toSerializableDiagnostics(answer.diagnostics());
        if (!diagnostics.isEmpty()) {
            generationDiagnostics.put(generationId, diagnostics);
            chatGenerationStateService.updateDiagnostics(generationId, diagnostics);
        }
        appendStreamChunk(userId, generationId, conversationId, answer.markdown());
        finalizeResponse(
                userId,
                userMessage,
                conversationId,
                generationId,
                responseFuture,
                responseBuilders.get(generationId),
                new LlmProviderRouter.StreamCompletion(answer.intent().name(), 0, 0, answer.markdown().length())
        );
    }

    private String resolveClientId(WebSocketSession session) {
        String clientId = chatSessionRegistry.getClientId(session);
        if (clientId != null && !clientId.isBlank()) {
            return clientId;
        }
        return session != null ? session.getId() : null;
    }

    private void runReActLoop(String userId,
                              String userMessage,
                              String conversationId,
                              String generationId,
                              List<Map<String, String>> history,
                              CompletableFuture<String> responseFuture) {
        ChatRequestTiming timing = generationTimings.get(generationId);
        String initialContext = "";
        if (shouldUseInitialPaperSearch(userMessage)) {
            if (timing != null) {
                timing.begin("retrieval");
            }
            InitialSearchOutcome initialSearchOutcome = runInitialPaperSearch(userId, userMessage, generationId, conversationId);
            if (timing != null) {
                timing.retrievalHitCount(initialSearchOutcome.hitCount());
                timing.end("retrieval");
            }
            if (initialSearchOutcome.noHit()) {
                logger.info("初始论文检索无命中，继续进入 ReAct 工具规划: generationId={}", generationId);
            }
            initialContext = initialSearchOutcome.context();
        }

        List<Map<String, Object>> messages = llmProviderRouter.buildReActMessages(
                userMessage,
                initialContext,
                history,
                buildRecentFeedbackGuidance(userId)
        );
        int executedToolCalls = 0;
        int totalPromptTokens = 0;
        int totalCompletionTokens = 0;

        for (int round = 1; round <= MAX_REACT_ROUNDS; round++) {
            if (finishCancelledGeneration(generationId, responseFuture, responseBuilders.get(generationId))) {
                return;
            }

            if (timing != null) {
                timing.begin("llm");
            }
            LlmProviderRouter.ReActTurn turn = streamReActTurnBlocking(
                    userId, conversationId, generationId, messages, agentToolRegistry.getTools());
            if (timing != null) {
                timing.end("llm");
            }
            if (turn == null) {
                // 上游 stream 被取消（如用户点 stop），保证内存映射被回收
                cleanupGenerationState(generationId, null);
                return;
            }
            totalPromptTokens += turn.promptTokens();
            totalCompletionTokens += turn.completionTokens();

            if (turn.toolCalls().isEmpty()) {
                finalizeResponse(userId, userMessage, conversationId, generationId, responseFuture,
                        responseBuilders.get(generationId),
                        new LlmProviderRouter.StreamCompletion(turn.finishReason(), totalPromptTokens, totalCompletionTokens, turn.content().length()));
                return;
            }

            messages.add(turn.assistantMessage());
            for (LlmProviderRouter.ToolCallDecision toolCall : turn.toolCalls()) {
                ExecutedToolResult executedToolResult;
                if (executedToolCalls >= MAX_REACT_TOOL_CALLS) {
                    executedToolResult = new ExecutedToolResult(
                            "工具调用预算已用尽，本次工具未执行。请基于已有 tool 结果给出最终回答。",
                            false
                    );
                    sendToolCallStatus(userId, generationId, conversationId, toolCall, "failed");
                } else {
                    executedToolResult = executeToolForReAct(userId, userMessage, generationId, conversationId, toolCall);
                    executedToolCalls++;
                }
                messages.add(toolMessage(toolCall.id(), executedToolResult.content()));
                if (executedToolResult.streamedToUser()) {
                    finalizeResponse(userId, userMessage, conversationId, generationId, responseFuture,
                            responseBuilders.get(generationId),
                            new LlmProviderRouter.StreamCompletion(
                                    "tool_streamed",
                                    totalPromptTokens,
                                    totalCompletionTokens,
                                    responseBuilders.get(generationId) != null ? responseBuilders.get(generationId).length() : 0
                            ));
                    return;
                }
            }
        }

        messages.add(Map.of(
                "role", "user",
                "content", "ReAct 轮次预算已用尽，请不要再调用工具，直接基于已有 tool 结果给出最终回答。"
        ));
        if (timing != null) {
            timing.begin("llm");
        }
        LlmProviderRouter.ReActTurn finalTurn = streamReActTurnBlocking(
                userId, conversationId, generationId, messages, List.of());
        if (timing != null) {
            timing.end("llm");
        }
        if (finalTurn == null) {
            cleanupGenerationState(generationId, null);
            return;
        }
        totalPromptTokens += finalTurn.promptTokens();
        totalCompletionTokens += finalTurn.completionTokens();
        finalizeResponse(userId, userMessage, conversationId, generationId, responseFuture,
                responseBuilders.get(generationId),
                new LlmProviderRouter.StreamCompletion(finalTurn.finishReason(), totalPromptTokens, totalCompletionTokens, finalTurn.content().length()));
    }

    private ExecutedToolResult executeToolForReAct(String userId,
                                                   String userMessage,
                                                   String generationId,
                                                   String conversationId,
                                                   LlmProviderRouter.ToolCallDecision toolCall) {
        sendToolCallStatus(userId, generationId, conversationId, toolCall, "executing");
        AtomicBoolean summaryStreamStarted = new AtomicBoolean(false);
        try {
            logger.info("ReAct 执行 Agent Tool: name={}, userId={}, generationId={}, toolCallId={}, args={}",
                    toolCall.name(), userId, generationId, toolCall.id(), toolCall.arguments());
            Consumer<String> toolChunkConsumer = "generate_summary".equals(toolCall.name())
                    ? chunk -> {
                        if (chunk == null || chunk.isEmpty()) {
                            return;
                        }
                        if (summaryStreamStarted.compareAndSet(false, true)) {
                            appendStreamChunk(userId, generationId, conversationId, "\n\n");
                        }
                        appendStreamChunk(userId, generationId, conversationId, chunk);
                    }
                    : null;
            ChatRequestTiming timing = generationTimings.get(generationId);
            if ("search_papers".equals(toolCall.name()) && timing != null) {
                timing.begin("retrieval");
            }
            AgentToolRegistry.ToolExecutionResult toolResult =
                    agentToolRegistry.executeTool(toolCall.name(), toolCall.arguments(), userId, toolChunkConsumer);
            if ("search_papers".equals(toolCall.name()) && timing != null) {
                timing.end("retrieval");
            }

            // search_papers 返回的 SearchResult 列表与模型 prompt 中的 [N] 编号一一对应，
            // 必须把它落到 generationReferenceMappings 里，否则前端点击引用拿不到 paperId/页码。
            if ("search_papers".equals(toolCall.name())) {
                if (timing != null) {
                    timing.retrievalHitCount(extractSearchResultCount(toolResult));
                }
                replaceReferencesFromSearchTool(generationId, userMessage, toolResult);
            }

            String content = toolResult.content();
            if (content == null || content.isBlank()) {
                content = "工具 " + toolCall.name() + " 执行成功，但没有返回可展示内容。";
            }
            sendToolCallStatus(userId, generationId, conversationId, toolCall, "success");
            return new ExecutedToolResult(content, toolResult.streamedToUser());
        } catch (Exception exception) {
            logger.warn("ReAct Agent Tool 执行失败，作为 tool message 返回模型: name={}, generationId={}",
                    toolCall.name(), generationId, exception);
            sendToolCallStatus(userId, generationId, conversationId, toolCall, "failed");
            // generate_summary 已经把部分摘要流给前端，再让模型重写会拼出"半个旧摘要 + 新摘要"。
            // 直接以失败提示收尾，让 ReAct 循环立即 finalize，避免数据不一致。
            if ("generate_summary".equals(toolCall.name()) && summaryStreamStarted.get()) {
                appendStreamChunk(userId, generationId, conversationId,
                        "\n\n（摘要流式生成中断：" + exception.getMessage() + "）");
                return new ExecutedToolResult(
                        "工具 " + toolCall.name() + " 已部分流式输出后失败: " + exception.getMessage(),
                        true
                );
            }
            return new ExecutedToolResult("工具 " + toolCall.name() + " 执行失败: " + exception.getMessage(), false);
        }
    }

    private int extractSearchResultCount(AgentToolRegistry.ToolExecutionResult toolResult) {
        if (toolResult == null || toolResult.data() == null) {
            return 0;
        }
        Object resultsObj = toolResult.data().get("results");
        return resultsObj instanceof List<?> results ? results.size() : 0;
    }

    private void replaceReferencesFromSearchTool(String generationId,
                                                 String userMessage,
                                                 AgentToolRegistry.ToolExecutionResult toolResult) {
        if (toolResult == null || toolResult.data() == null) {
            return;
        }
        Object resultsObj = toolResult.data().get("results");
        if (!(resultsObj instanceof List<?> rawList) || rawList.isEmpty()) {
            return;
        }

        Map<Integer, ReferenceInfo> mapping = new HashMap<>();
        int referenceNumber = 1;
        String retrievalQuery = toolResult.data().get("query") instanceof String query && !query.isBlank()
                ? query
                : userMessage;
        for (Object item : rawList) {
            if (!(item instanceof SearchResult result) || result.getPaperId() == null) {
                continue;
            }
            String paperLabel = result.getPaperTitle() != null ? result.getPaperTitle() : "unknown";
            mapping.put(referenceNumber, buildReferenceInfo(result, paperLabel, retrievalQuery));
            referenceNumber++;
        }
        if (mapping.isEmpty()) {
            return;
        }
        // 模型每次 search_papers 都会拿到 [1]..[K] 重新编号，因此按"覆盖"语义保存最新一次的引用映射。
        generationReferenceMappings.put(generationId, mapping);
        chatGenerationStateService.updateReferenceMappings(generationId, toSerializableReferenceMappings(mapping));
        logger.info("ReAct search_papers 引用映射已刷新: generationId={}, count={}", generationId, mapping.size());
    }

    private InitialSearchOutcome runInitialPaperSearch(String userId,
                                                           String userMessage,
                                                           String generationId,
                                                           String conversationId) {
        LlmProviderRouter.ToolCallDecision toolCall = new LlmProviderRouter.ToolCallDecision(
                INITIAL_SEARCH_TOOL_CALL_ID,
                "search_papers",
                Map.of("query", userMessage, "pageBatchSize", INITIAL_SEARCH_PAGE_BATCH_SIZE)
        );
        sendToolCallStatus(userId, generationId, conversationId, toolCall, "executing");

        PaperRetrievalService.RetrievalResult retrievalResult = paperRetrievalService.retrieve(
                userMessage,
                userId,
                RetrievalBudget.forPageBatch(INITIAL_SEARCH_PAGE_BATCH_SIZE)
        );
        List<String> queries = retrievalResult.attemptedQueries();

        sendToolCallStatus(userId, generationId, conversationId, toolCall, "success");
        if (retrievalResult.finalHitCount() == 0) {
            logger.info("初始论文检索无命中: generationId={}, queries={}", generationId, queries);
            return InitialSearchOutcome.noHitOutcome();
        }

        List<SearchResult> mergedResults = retrievalResult.results();
        String retrievalQuery = String.join(" | ", queries);
        String context = buildContext(mergedResults, generationId, retrievalQuery);
        logger.info("初始论文检索命中: generationId={}, queries={}, resultCount={}",
                generationId, queries, mergedResults.size());
        return InitialSearchOutcome.withContext(context, mergedResults.size());
    }

    static boolean shouldUseInitialPaperSearch(String userMessage) {
        if (isSmalltalkMessage(userMessage)) {
            return false;
        }
        String normalized = normalizeEvidenceTextStatic(userMessage);
        if (normalized.isBlank()) {
            return false;
        }
        String lower = normalized.toLowerCase(Locale.ROOT);
        if (lower.contains("不要查论文") || lower.contains("不用查论文")
                || lower.contains("别查论文") || lower.contains("直接回答")) {
            return false;
        }
        return !lower.matches("^(你好|您好|hello|hi|谢谢|谢了|再见|拜拜)[!！。,.，\\s]*$");
    }

    static boolean isSmalltalkMessage(String userMessage) {
        String normalized = normalizeChatRouteText(userMessage);
        return switch (normalized) {
            case "hi", "hello", "hey", "你好", "您好", "在吗", "谢谢", "thanks", "ok", "好的" -> true;
            default -> false;
        };
    }

    private static String normalizeChatRouteText(String userMessage) {
        if (userMessage == null) {
            return "";
        }
        return userMessage
                .trim()
                .toLowerCase(Locale.ROOT)
                .replaceAll("[\\s!！?？。,.，;；:：、\"'“”‘’()（）\\[\\]{}<>《》]+", "");
    }

    static List<String> buildInitialPaperQueries(String userMessage) {
        String original = normalizeEvidenceTextStatic(userMessage);
        if (original.isBlank()) {
            return List.of();
        }

        String focused = original
                .replaceFirst("^(你知道|你懂|你了解|请问|帮我查一下|查一下|说说|解释一下|介绍一下)", "")
                .replaceFirst("(是什么|是啥|吗|么|呢|\\?)$", "")
                .trim();

        List<String> queries = new ArrayList<>();
        if (!focused.isBlank()) {
            queries.add(focused);
        }
        if (!queries.contains(original)) {
            queries.add(original);
        }
        return queries;
    }

    private record InitialSearchOutcome(String context, boolean noHit, int hitCount) {
        private static InitialSearchOutcome withContext(String context, int hitCount) {
            return new InitialSearchOutcome(context == null ? "" : context, false, hitCount);
        }

        private static InitialSearchOutcome noHitOutcome() {
            return new InitialSearchOutcome("", true, 0);
        }
    }

    private record ExecutedToolResult(String content, boolean streamedToUser) {
    }

    private Map<String, Object> toolMessage(String toolCallId, String content) {
        Map<String, Object> message = new HashMap<>();
        message.put("role", "tool");
        message.put("tool_call_id", toolCallId == null ? "" : toolCallId);
        message.put("content", content == null ? "" : content);
        return message;
    }

    private LlmProviderRouter.ReActTurn streamReActTurnBlocking(String userId,
                                                                String conversationId,
                                                                String generationId,
                                                                List<Map<String, Object>> messages,
                                                                List<AgentToolRegistry.AgentTool> tools) {
        CompletableFuture<LlmProviderRouter.ReActTurn> turnFuture = new CompletableFuture<>();
        LlmProviderRouter.StreamHandle streamHandle = llmProviderRouter.streamReActTurn(
                userId,
                messages,
                tools,
                REACT_MAX_COMPLETION_TOKENS,
                chunk -> appendStreamChunk(userId, generationId, conversationId, chunk),
                turnFuture::completeExceptionally,
                turnFuture::complete
        );
        activeStreams.put(generationId, streamHandle);

        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(GENERATION_COMPLETION_TIMEOUT_SECONDS);
        try {
            while (true) {
                if (isGenerationCancelled(generationId)) {
                    streamHandle.cancel();
                    return null;
                }
                long remainingNanos = deadline - System.nanoTime();
                if (remainingNanos <= 0) {
                    streamHandle.cancel();
                    throw new RuntimeException("模型响应超时，请稍后重试");
                }
                try {
                    long waitMillis = Math.min(TimeUnit.NANOSECONDS.toMillis(remainingNanos), 200L);
                    return turnFuture.get(Math.max(waitMillis, 1L), TimeUnit.MILLISECONDS);
                } catch (TimeoutException ignored) {
                    // 短轮询用于及时响应用户停止生成。
                }
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            streamHandle.cancel();
            throw new RuntimeException("模型响应被中断", exception);
        } catch (ExecutionException exception) {
            streamHandle.cancel();
            Throwable cause = exception.getCause() == null ? exception : exception.getCause();
            if (cause instanceof RuntimeException runtimeException) {
                throw runtimeException;
            }
            throw new RuntimeException("ReAct 流式模型回合调用失败", cause);
        } finally {
            activeStreams.remove(generationId, streamHandle);
        }
    }

    private void appendStreamChunk(String userId, String generationId, String conversationId, String chunk) {
        if (chunk == null || chunk.isEmpty() || isGenerationCancelled(generationId)) {
            return;
        }
        StringBuilder responseBuilder = responseBuilders.get(generationId);
        if (responseBuilder != null) {
            responseBuilder.append(chunk);
        }
        chatGenerationStateService.appendChunk(generationId, chunk);
        sendResponseChunk(userId, generationId, conversationId, chunk);
    }

    private void submitCompletionMonitor(String userId, String userMessage, String conversationId, String generationId,
                                         CompletableFuture<String> responseFuture) {
        try {
            chatMonitorExecutor.execute(() -> {
                try {
                    if (finishCancelledGeneration(generationId, responseFuture, responseBuilders.get(generationId))) {
                        return;
                    }

                    responseFuture.get(GENERATION_COMPLETION_TIMEOUT_SECONDS, TimeUnit.SECONDS);
                } catch (TimeoutException e) {
                    if (finishCancelledGeneration(generationId, responseFuture, responseBuilders.get(generationId))) {
                        return;
                    }
                    RuntimeException exception = new RuntimeException("模型响应超时，请稍后重试");
                    if (responseFuture.completeExceptionally(exception)) {
                        handleError(userId, generationId, exception);
                        sendCompletionNotification(userId, generationId, conversationId, true, false);
                        chatGenerationStateService.markFailed(generationId, exception.getMessage());
                        cleanupGenerationState(generationId, exception);
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } catch (ExecutionException ignored) {
                    // 上游错误分支已经处理并完成了当前 future，这里只负责等待兜底。
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    if (responseFuture.completeExceptionally(e)) {
                        chatGenerationStateService.markFailed(generationId, e.getMessage());
                        cleanupGenerationState(generationId, e);
                    }
                }
            });
        } catch (RejectedExecutionException ex) {
            logger.warn("聊天监控线程池已满，generationId: {}", generationId);
            RuntimeException busyException = new RuntimeException("系统繁忙，请稍后重试");
            handleError(userId, generationId, busyException);
            chatGenerationStateService.markFailed(generationId, busyException.getMessage());
            cleanupGenerationState(generationId, ex);
        }
    }

    private void finalizeResponse(String userId, String userMessage, String conversationId, String generationId,
                                  CompletableFuture<String> responseFuture,
                                  StringBuilder responseBuilder,
                                  LlmProviderRouter.StreamCompletion completion) {
        if (finishCancelledGeneration(generationId, responseFuture, responseBuilder)) {
            return;
        }
        if (responseBuilder == null) {
            if (responseFuture.isDone() || !responseFutures.containsKey(generationId)) {
                return;
            }
            RuntimeException exception = new RuntimeException("响应构建器为空");
            if (responseFuture.completeExceptionally(exception)) {
                handleError(userId, generationId, exception);
                sendCompletionNotification(userId, generationId, conversationId, true, false);
                chatGenerationStateService.markFailed(generationId, exception.getMessage());
                cleanupGenerationState(generationId, exception);
            }
            return;
        }
        String completeResponse = responseBuilder.toString();
        if (completeResponse.isBlank()) {
            RuntimeException exception = new RuntimeException("模型未返回有效内容，请稍后重试");
            if (responseFuture.completeExceptionally(exception)) {
                handleError(userId, generationId, exception);
                sendCompletionNotification(userId, generationId, conversationId, true, false);
                chatGenerationStateService.markFailed(generationId, exception.getMessage());
                cleanupGenerationState(generationId, exception);
            }
            return;
        }
        if (!responseFuture.complete(completeResponse)) {
            return;
        }
        logger.info("模型回答收尾: generationId={}, conversationId={}, answerChars={}, finishReason={}, promptTokens={}, completionTokens={}",
                generationId,
                conversationId,
                completeResponse.length(),
                completion != null && completion.finishReason() != null ? completion.finishReason() : "unknown",
                completion != null ? completion.promptTokens() : 0,
                completion != null ? completion.completionTokens() : 0);
        Map<Integer, ReferenceInfo> referenceMappings = filterReferenceMappingsForResponse(
                generationReferenceMappings.get(generationId),
                completeResponse
        );
        if (referenceMappings.isEmpty()) {
            generationReferenceMappings.remove(generationId);
        } else {
            generationReferenceMappings.put(generationId, referenceMappings);
        }
        ChatRequestTiming timing = generationTimings.get(generationId);
        if (timing != null) {
            timing.citationCount(referenceMappings.size());
            timing.mark("reference_mapping_saved");
        }
        // 先把消息事务性地落 MySQL；只有 MySQL 成功后才写 Redis 短期会话历史，
        // 否则两个数据源会出现一边有记录、一边没有的不一致状态。
        boolean persisted = persistConversation(userId, userMessage, completeResponse, conversationId, referenceMappings);
        if (persisted) {
            updateConversationHistory(conversationId, userMessage, completeResponse, referenceMappings);
        } else {
            logger.warn("MySQL 落库失败，跳过 Redis 会话历史写入以保持两端一致: generationId={}, conversationId={}",
                    generationId, conversationId);
        }
        chatGenerationStateService.markCompleted(generationId, toSerializableReferenceMappings(referenceMappings));
        sendCompletionNotification(userId, generationId, conversationId, false, !persisted);
        if (timing != null) {
            timing.mark("response_sent");
            timing.log(logger, conversationId, generationId);
        }
        logger.info("对话存储信息 - Redis键: {}, 值: {}", "user:" + userId + ":current_conversation", conversationId);
        cleanupGenerationState(generationId, null);
        logger.info("消息处理完成，用户ID: {}", userId);
    }

    private boolean persistConversation(String userId, String userMessage, String completeResponse, String conversationId,
                                        Map<Integer, ReferenceInfo> referenceMappings) {
        try {
            Long userIdLong = Long.parseLong(userId);
            conversationService.recordConversation(
                    userIdLong,
                    userMessage,
                    completeResponse,
                    conversationId,
                    toSerializableReferenceMappings(referenceMappings)
            );
            return true;
        } catch (Exception e) {
            logger.error("持久化对话历史失败: userId={}, conversationId={}", userId, conversationId, e);
            return false;
        }
    }

    private void cleanupGenerationState(String generationId, Throwable throwable) {
        responseBuilders.remove(generationId);
        generationClientIds.remove(generationId);
        generationReferenceMappings.remove(generationId);
        generationDiagnostics.remove(generationId);
        generationTimings.remove(generationId);
        stopFlags.remove(generationId);
        activeStreams.remove(generationId);
        cancelledGenerations.remove(generationId);
        CompletableFuture<String> future = responseFutures.remove(generationId);
        if (throwable != null && future != null && !future.isDone()) {
            future.completeExceptionally(throwable);
        }
    }

    private boolean finishCancelledGeneration(String generationId,
                                              CompletableFuture<String> responseFuture,
                                              StringBuilder responseBuilder) {
        if (!isGenerationCancelled(generationId)) {
            return false;
        }

        if (!responseFuture.isDone()) {
            responseFuture.complete(responseBuilder != null ? responseBuilder.toString() : "");
        }
        cleanupGenerationState(generationId, null);
        logger.info("生成任务已取消并停止后续收尾逻辑: generationId={}", generationId);
        return true;
    }

    private boolean isGenerationCancelled(String generationId) {
        return generationId != null && (cancelledGenerations.contains(generationId) || Boolean.TRUE.equals(stopFlags.get(generationId)));
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);

        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }

        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        List<Map<String, Object>> records = getConversationHistoryRecords(conversationId);
        List<Map<String, String>> history = new ArrayList<>();
        for (Map<String, Object> message : records) {
            Map<String, String> normalized = new HashMap<>();
            normalized.put("role", String.valueOf(message.getOrDefault("role", "")));
            normalized.put("content", String.valueOf(message.getOrDefault("content", "")));
            Object timestamp = message.get("timestamp");
            if (timestamp != null) {
                normalized.put("timestamp", String.valueOf(timestamp));
            }
            history.add(normalized);
        }
        return history;
    }

    private String buildRecentFeedbackGuidance(String userId) {
        if (userId == null || userId.isBlank()) {
            return "";
        }
        try {
            Map<Object, Object> feedbackEntries = redisTemplate.opsForHash().entries("feedback:" + userId);
            if (feedbackEntries == null || feedbackEntries.isEmpty()) {
                return "";
            }

            StringBuilder guidance = new StringBuilder("近期用户对回答的显式反馈如下，按时间倒序排列，越靠前越新。")
                    .append("后续回答需要参考这些偏好：good 表示用户认可这类回答方式，bad 表示需要避免类似问题；")
                    .append("如果同一轮回答既有 good 又有 bad，以最新一条为准。\n");
            feedbackEntries.entrySet().stream()
                    .sorted(Comparator.comparingLong(entry -> -parseFeedbackTimestamp(entry.getKey())))
                    .limit(5)
                    .forEach(entry -> guidance.append("- ")
                            .append("feedbackTime=")
                            .append(entry.getKey())
                            .append("; ")
                            .append(entry.getValue())
                            .append("\n"));
            return guidance.toString().trim();
        } catch (Exception exception) {
            logger.warn("读取用户反馈上下文失败: userId={}", userId, exception);
            return "";
        }
    }

    private long parseFeedbackTimestamp(Object value) {
        if (value == null) {
            return 0L;
        }
        try {
            return Long.parseLong(String.valueOf(value));
        } catch (NumberFormatException exception) {
            return 0L;
        }
    }

    private List<Map<String, Object>> getConversationHistoryRecords(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }

            List<Map<String, Object>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, Object>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response,
                                           Map<Integer, ReferenceInfo> referenceMapping) {
        String key = "conversation:" + conversationId;
        List<Map<String, Object>> history = getConversationHistoryRecords(conversationId);

        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));

        // 添加用户消息（带时间戳）
        Map<String, Object> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);

        // 添加助手回复（带时间戳）
        Map<String, Object> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        if (referenceMapping != null && !referenceMapping.isEmpty()) {
            assistantMsgMap.put("referenceMappings", toSerializableReferenceMappings(referenceMapping));
        }
        history.add(assistantMsgMap);

        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }

        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private Map<String, Map<String, Object>> toSerializableReferenceMappings(Map<Integer, ReferenceInfo> referenceMapping) {
        Map<String, Map<String, Object>> serialized = new HashMap<>();
        if (referenceMapping == null || referenceMapping.isEmpty()) {
            return serialized;
        }
        for (Map.Entry<Integer, ReferenceInfo> entry : referenceMapping.entrySet()) {
            ReferenceInfo detail = entry.getValue();
            Map<String, Object> item = new HashMap<>();
            item.put("paperId", detail.paperId());
            item.put("paperTitle", detail.paperTitle());
            item.put("originalFilename", detail.originalFilename());
            item.put("pageNumber", detail.pageNumber());
            item.put("anchorText", detail.anchorText());
            item.put("retrievalMode", detail.retrievalMode());
            item.put("retrievalLabel", detail.retrievalLabel());
            item.put("retrievalQuery", detail.retrievalQuery());
            item.put("matchedChunkText", detail.matchedChunkText());
            item.put("evidenceSnippet", detail.evidenceSnippet());
            item.put("score", detail.score());
            item.put("chunkId", detail.chunkId());
            item.put("elementType", detail.elementType());
            item.put("sectionTitle", detail.sectionTitle());
            item.put("sectionLevel", detail.sectionLevel());
            item.put("bboxJson", detail.bboxJson());
            item.put("parserName", detail.parserName());
            item.put("parserVersion", detail.parserVersion());
            item.put("sourceKind", detail.sourceKind());
            item.put("tableId", detail.tableId());
            item.put("figureId", detail.figureId());
            item.put("formulaId", detail.formulaId());
            item.put("evidenceRole", detail.evidenceRole());
            item.put("retrievalRoute", detail.retrievalRoute());
            item.put("intent", detail.intent());
            item.put("rankReason", detail.rankReason());
            item.put("tableText", detail.tableText());
            item.put("tableMarkdown", detail.tableMarkdown());
            item.put("tableScreenshotAvailable", detail.tableScreenshotAvailable());
            item.put("sourceType", detail.sourceType());
            item.put("evidenceAssetLevel", detail.evidenceAssetLevel());
            item.put("pdfEvidenceAvailable", detail.pdfEvidenceAvailable());
            item.put("structuredImport", detail.structuredImport());
            item.put("evalImport", detail.evalImport());
            item.put("pageScreenshotAvailable", detail.pageScreenshotAvailable());
            item.put("figureScreenshotAvailable", detail.figureScreenshotAvailable());
            item.put("assetWarnings", detail.assetWarnings());
            serialized.put(String.valueOf(entry.getKey()), item);
        }
        return serialized;
    }

    private Map<String, Object> toSerializableDiagnostics(PaperAnswerService.AnswerDiagnostics diagnostics) {
        if (diagnostics == null) {
            return Map.of();
        }
        return objectMapper.convertValue(diagnostics, new TypeReference<Map<String, Object>>() {});
    }

    static Map<Integer, ReferenceInfo> filterReferenceMappingsForResponse(Map<Integer, ReferenceInfo> referenceMapping,
                                                                          String response) {
        Map<Integer, ReferenceInfo> filtered = new LinkedHashMap<>();
        if (referenceMapping == null || referenceMapping.isEmpty() || response == null || response.isBlank()) {
            return filtered;
        }

        Matcher matcher = CITED_REFERENCE_PATTERN.matcher(response);
        while (matcher.find()) {
            try {
                Integer referenceNumber = Integer.parseInt(matcher.group(1));
                ReferenceInfo detail = referenceMapping.get(referenceNumber);
                if (detail != null) {
                    filtered.putIfAbsent(referenceNumber, detail);
                }
            } catch (NumberFormatException ignored) {
                // The regex only captures digits; keep this branch defensive for future pattern changes.
            }
        }
        return filtered;
    }

    private String buildContext(List<SearchResult> searchResults, String generationId, String userMessage) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 LLM provider 按"无检索结果"逻辑处理
            return "";
        }

        // 创建当前生成任务的引用映射
        Map<Integer, ReferenceInfo> referenceMapping = new HashMap<>();

        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet.length() > MAX_CONTEXT_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_CONTEXT_SNIPPET_LEN) + "…";
            }
            String paperLabel = result.getPaperTitle() != null ? result.getPaperTitle() : "unknown";
            String paperId = result.getPaperId();

            context.append("[").append(i + 1).append("]\n")
                    .append("paperTitle: ").append(paperLabel).append("\n")
                    .append("sourceKind: ").append(result.getSourceKind() != null ? result.getSourceKind() : "TEXT").append("\n");
            if (result.getPageNumber() != null && result.getPageNumber() > 0) {
                context.append("pageNumber: ").append(result.getPageNumber()).append("\n");
            }
            if (result.getSectionTitle() != null && !result.getSectionTitle().isBlank()) {
                context.append("sectionTitle: ").append(result.getSectionTitle()).append("\n");
            }
            if (result.getRetrievalRoute() != null && !result.getRetrievalRoute().isBlank()) {
                context.append("retrievalRoute: ").append(result.getRetrievalRoute()).append("\n");
            }
            if (result.getScore() != null) {
                context.append("score: ").append(String.format(Locale.ROOT, "%.4f", result.getScore())).append("\n");
            }
            context.append("matchedText: ").append(snippet).append("\n");

            // 保存引用编号到论文证据的映射
            if (paperId != null) {
                ReferenceInfo detail = buildReferenceInfo(result, paperLabel, userMessage);
                referenceMapping.put(i + 1, detail);
                logger.info("引用映射: generationId={}, 引用编号#{}={}, paperTitle={}, paperId={}, page={}, retrievalMode={}, chunkId={}",
                    generationId, i + 1, paperLabel, paperId, result.getPageNumber(), detail.retrievalMode(), detail.chunkId());
            }
        }

        // 保存当前生成任务的引用映射
        generationReferenceMappings.put(generationId, referenceMapping);
        chatGenerationStateService.updateReferenceMappings(generationId, toSerializableReferenceMappings(referenceMapping));
        logger.info("保存生成任务 {} 的引用映射，共 {} 条: {}", generationId, referenceMapping.size(), referenceMapping);

        return context.toString();
    }

    private void sendGenerationStart(String userId, String generationId, String conversationId) {
        sendJsonToGenerationClient(userId, generationId, Map.of(
                "type", "start",
                "generationId", generationId,
                "conversationId", conversationId,
                "timestamp", System.currentTimeMillis()
        ));
    }

    private void sendResponseChunk(String userId, String generationId, String conversationId, String chunk) {
        if (Boolean.TRUE.equals(stopFlags.get(generationId))) {
            logger.debug("检测到停止标志，跳过发送响应块: generationId={}", generationId);
            return;
        }

        sendJsonToGenerationClient(userId, generationId, Map.of(
                "type", "chunk",
                "generationId", generationId,
                "conversationId", conversationId,
                "chunk", chunk
        ));
    }

    private void sendToolCallStatus(String userId,
                                    String generationId,
                                    String conversationId,
                                    LlmProviderRouter.ToolCallDecision toolCall,
                                    String status) {
        Map<String, Object> payload = new HashMap<>();
        payload.put("type", "tool_call");
        payload.put("tool", toolCall.name());
        payload.put("toolCallId", toolCall.id());
        payload.put("status", status);
        payload.put("generationId", generationId);
        payload.put("conversationId", conversationId);
        payload.put("timestamp", System.currentTimeMillis());
        sendJsonToGenerationClient(userId, generationId, payload);
    }

    private void sendCompletionNotification(String userId,
                                            String generationId,
                                            String conversationId,
                                            boolean failed,
                                            boolean persistenceDegraded) {
        Map<String, Object> notification = new HashMap<>();
        notification.put("type", "completion");
        notification.put("generationId", generationId);
        notification.put("conversationId", conversationId);
        notification.put("status", failed ? "failed" : "finished");
        notification.put("message", failed ? "响应已中断" : "响应已完成");
        notification.put("timestamp", System.currentTimeMillis());
        notification.put("date", java.time.LocalDateTime.now().toString());
        if (!failed) {
            Map<Integer, ReferenceInfo> referenceMappings = generationReferenceMappings.get(generationId);
            if (referenceMappings != null && !referenceMappings.isEmpty()) {
                notification.put("referenceMappings", toSerializableReferenceMappings(referenceMappings));
            }
            Map<String, Object> diagnostics = generationDiagnostics.get(generationId);
            if (diagnostics != null && !diagnostics.isEmpty()) {
                notification.put("diagnostics", diagnostics);
            }
        }
        if (persistenceDegraded) {
            notification.put("persistenceDegraded", true);
            notification.put("persistenceWarning", "本次回复未能持久化到数据库，刷新后可能无法在历史中找到。");
        }
        sendJsonToGenerationClient(userId, generationId, notification);
    }

    private void handleError(String userId, String generationId, Throwable error) {
        handleError(userId, null, generationId, error);
    }

    private void handleError(String userId, String clientId, String generationId, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        Map<String, Object> errorResponse = new HashMap<>();
        errorResponse.put("type", "error");
        errorResponse.put("generationId", generationId);
        errorResponse.put("error", "AI服务暂时不可用，请稍后重试");
        sendJsonToGenerationOrClient(userId, clientId, generationId, errorResponse);
    }

    private void sendRateLimitMessage(String userId, String clientId, String generationId, RateLimitExceededException exception) {
        Map<String, Object> payload = new HashMap<>();
        payload.put("type", "error");
        payload.put("generationId", generationId);
        payload.put("code", 429);
        payload.put("message", exception.getMessage());
        payload.put("retryAfterSeconds", exception.getRetryAfterSeconds());
        sendJsonToGenerationOrClient(userId, clientId, generationId, payload);
    }

    private void sendJsonToGenerationOrClient(String userId,
                                              String clientId,
                                              String generationId,
                                              Map<String, ?> payload) {
        if (generationId != null && !generationId.isBlank() && generationClientIds.containsKey(generationId)) {
            sendJsonToGenerationClient(userId, generationId, payload);
            return;
        }
        sendJsonToClient(userId, clientId, payload);
    }

    private void sendJsonToGenerationClient(String userId, String generationId, Map<String, ?> payload) {
        String clientId = generationClientIds.get(generationId);
        if (clientId == null || clientId.isBlank()) {
            logger.debug("生成任务 {} 没有绑定 clientId，跳过 WebSocket 定向发送", generationId);
            return;
        }
        chatSessionRegistry.sendJsonToClient(userId, clientId, payload);
    }

    private void sendJsonToClient(String userId, String clientId, Map<String, ?> payload) {
        if (clientId == null || clientId.isBlank()) {
            logger.debug("用户 {} 的请求 clientId 为空，跳过 WebSocket 定向发送", userId);
            return;
        }
        chatSessionRegistry.sendJsonToClient(userId, clientId, payload);
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, String generationId) {
        stopResponse(userId, generationId, null);
    }

    public void stopResponse(String userId, String generationId, WebSocketSession requesterSession) {
        String requesterClientId = resolveClientId(requesterSession);
        String resolvedGenerationId = generationId;
        if (resolvedGenerationId == null || resolvedGenerationId.isBlank()) {
            resolvedGenerationId = chatGenerationStateService.getActiveGenerationForUser(userId)
                    .map(ChatGenerationStateService.GenerationSnapshot::generationId)
                    .orElse(null);
        }

        if (resolvedGenerationId == null || resolvedGenerationId.isBlank()) {
            logger.warn("收到停止请求但未找到活动生成任务，用户ID: {}", userId);
            return;
        }
        final String targetGenerationId = resolvedGenerationId;
        String targetClientId = generationClientIds.getOrDefault(targetGenerationId, requesterClientId);

        logger.info("收到停止请求，用户ID: {}，generationId: {}", userId, targetGenerationId);

        // 设置停止标志
        cancelledGenerations.add(targetGenerationId);
        stopFlags.put(targetGenerationId, true);
        chatGenerationStateService.markCancelled(targetGenerationId);
        LlmProviderRouter.StreamHandle streamHandle = activeStreams.get(targetGenerationId);
        if (streamHandle != null) {
            streamHandle.cancel();
        }
        CompletableFuture<String> responseFuture = responseFutures.get(targetGenerationId);
        if (responseFuture != null && !responseFuture.isDone()) {
            responseFuture.completeExceptionally(new CancellationException("响应已停止"));
        }

        sendJsonToClient(userId, targetClientId, Map.of(
                "type", "stop",
                "generationId", targetGenerationId,
                "message", "响应已停止",
                "timestamp", System.currentTimeMillis(),
                "date", java.time.Instant.now().toString()
        ));

        logger.info("已停止上游流式生成: generationId={}", targetGenerationId);
    }

    /**
     * 根据生成任务和引用编号获取论文标识
     *
     * @param generationId 生成任务ID
     * @param referenceNumber 引用编号
     * @return paperId，如果找不到则返回null
     */
    public String getReferencePaperId(String generationId, int referenceNumber) {
        ReferenceInfo detail = getReferenceDetail(generationId, referenceNumber);
        return detail != null ? detail.paperId() : null;
    }

    public ReferenceInfo getReferenceDetail(String generationId, int referenceNumber) {
        logger.info("查询引用证据: generationId={}, referenceNumber=#{}", generationId, referenceNumber);

        Map<Integer, ReferenceInfo> referenceMapping = generationReferenceMappings.get(generationId);
        if (referenceMapping == null) {
            referenceMapping = chatGenerationStateService.getGeneration(generationId)
                    .map(ChatGenerationStateService.GenerationSnapshot::referenceMappings)
                    .filter(mappings -> !mappings.isEmpty())
                    .map(this::toReferenceInfoMap)
                    .orElse(null);
        }
        if (referenceMapping == null) {
            logger.error("未找到生成任务 {} 的引用映射，当前所有生成任务: {}", generationId, generationReferenceMappings.keySet());
            return null;
        }

        logger.info("生成任务 {} 的引用映射内容: {}", generationId, referenceMapping);

        ReferenceInfo detail = referenceMapping.get(referenceNumber);
        if (detail == null) {
            logger.error("生成任务 {} 中未找到引用编号 #{}, 可用的引用编号: {}", generationId, referenceNumber, referenceMapping.keySet());
            return null;
        }

        logger.info("成功找到引用映射: generationId={}, referenceNumber=#{}, paperId={}, pageNumber={}",
                generationId, referenceNumber, detail.paperId(), detail.pageNumber());
        return detail;
    }

    private Map<Integer, ReferenceInfo> toReferenceInfoMap(Map<String, Map<String, Object>> serializedMappings) {
        Map<Integer, ReferenceInfo> referenceMap = new HashMap<>();
        for (Map.Entry<String, Map<String, Object>> entry : serializedMappings.entrySet()) {
            Map<String, Object> item = entry.getValue();
            referenceMap.put(Integer.parseInt(entry.getKey()), new ReferenceInfo(
                    (String) item.get("paperId"),
                    (String) item.get("paperTitle"),
                    (String) item.get("originalFilename"),
                    item.get("pageNumber") instanceof Number number ? number.intValue() : null,
                    (String) item.get("anchorText"),
                    (String) item.get("retrievalMode"),
                    (String) item.get("retrievalLabel"),
                    (String) item.get("retrievalQuery"),
                    (String) item.get("matchedChunkText"),
                    (String) item.get("evidenceSnippet"),
                    item.get("score") instanceof Number number ? number.doubleValue() : null,
                    item.get("chunkId") instanceof Number number ? number.intValue() : null,
                    (String) item.get("elementType"),
                    (String) item.get("sectionTitle"),
                    item.get("sectionLevel") instanceof Number number ? number.intValue() : null,
                    (String) item.get("bboxJson"),
                    (String) item.get("parserName"),
                    (String) item.get("parserVersion"),
                    (String) item.get("sourceKind"),
                    (String) item.get("tableId"),
                    (String) item.get("figureId"),
                    (String) item.get("formulaId"),
                    (String) item.get("evidenceRole"),
                    (String) item.get("retrievalRoute"),
                    (String) item.get("intent"),
                    (String) item.get("rankReason"),
                    (String) item.get("tableText"),
                    (String) item.get("tableMarkdown"),
                    item.get("tableScreenshotAvailable") instanceof Boolean value && value,
                    (String) item.get("sourceType"),
                    (String) item.get("evidenceAssetLevel"),
                    item.get("pdfEvidenceAvailable") instanceof Boolean value && value,
                    item.get("structuredImport") instanceof Boolean value && value,
                    item.get("evalImport") instanceof Boolean value && value,
                    item.get("pageScreenshotAvailable") instanceof Boolean value && value,
                    item.get("figureScreenshotAvailable") instanceof Boolean value && value,
                    stringListValue(item.get("assetWarnings"))
            ));
        }
        return referenceMap;
    }

    private List<String> stringListValue(Object raw) {
        if (!(raw instanceof List<?> rawList)) {
            return List.of();
        }
        return rawList.stream()
                .filter(value -> value != null && !String.valueOf(value).isBlank())
                .map(String::valueOf)
                .toList();
    }

    private ReferenceInfo buildReferenceInfo(SearchResult result, String paperLabel, String userMessage) {
        String matchedChunkText = trimToMaxLength(
                result.getMatchedChunkText() != null ? result.getMatchedChunkText() : result.getTextContent(),
                MAX_MATCHED_CHUNK_LEN
        );
        String evidenceSnippet = buildEvidenceSnippet(userMessage, result.getAnchorText(), matchedChunkText);

        return new ReferenceInfo(
                result.getPaperId(),
                paperLabel,
                result.getOriginalFilename(),
                result.getPageNumber(),
                result.getAnchorText(),
                result.getRetrievalMode(),
                buildRetrievalLabel(result.getRetrievalMode()),
                normalizeEvidenceText(result.getRetrievalQuery() != null ? result.getRetrievalQuery() : userMessage),
                matchedChunkText,
                evidenceSnippet,
                result.getScore(),
                result.getChunkId(),
                result.getElementType(),
                result.getSectionTitle(),
                result.getSectionLevel(),
                result.getBboxJson(),
                result.getParserName(),
                result.getParserVersion(),
                result.getSourceKind(),
                result.getTableId(),
                result.getFigureId(),
                result.getFormulaId(),
                result.getEvidenceRole(),
                result.getRetrievalRoute(),
                result.getIntent(),
                result.getRankReason(),
                result.getTableText(),
                result.getTableMarkdown(),
                Boolean.TRUE.equals(result.getTableScreenshotAvailable()),
                result.getSourceType(),
                result.getEvidenceAssetLevel(),
                Boolean.TRUE.equals(result.getPdfEvidenceAvailable()),
                Boolean.TRUE.equals(result.getStructuredImport()),
                Boolean.TRUE.equals(result.getEvalImport()),
                Boolean.TRUE.equals(result.getPageScreenshotAvailable()),
                Boolean.TRUE.equals(result.getFigureScreenshotAvailable()),
                result.getAssetWarnings()
        );
    }

    private String buildRetrievalLabel(String retrievalMode) {
        if ("TEXT_ONLY".equalsIgnoreCase(retrievalMode)) {
            return "关键词召回";
        }
        return "混合召回（语义相关 + 关键词命中）";
    }

    private String buildEvidenceSnippet(String userMessage, String anchorText, String matchedChunkText) {
        String normalizedAnchorText = normalizeEvidenceText(anchorText);
        if (!normalizedAnchorText.isBlank()) {
            return trimToMaxLength(normalizedAnchorText, MAX_EVIDENCE_SNIPPET_LEN);
        }

        String normalizedMatchedChunk = normalizeEvidenceText(matchedChunkText);
        if (normalizedMatchedChunk.isBlank()) {
            String normalizedUserMessage = normalizeEvidenceText(userMessage);
            if (!normalizedUserMessage.isBlank()) {
                return trimToMaxLength(normalizedUserMessage, MAX_EVIDENCE_SNIPPET_LEN);
            }
            return "";
        }

        String[] sentences = normalizedMatchedChunk.split("(?<=[。！？!?；;])");
        for (String sentence : sentences) {
            String trimmedSentence = sentence.trim();
            if (trimmedSentence.length() >= 12) {
                return trimToMaxLength(trimmedSentence, MAX_EVIDENCE_SNIPPET_LEN);
            }
        }

        return trimToMaxLength(normalizedMatchedChunk, MAX_EVIDENCE_SNIPPET_LEN);
    }

    private String trimToMaxLength(String value, int maxLength) {
        String normalized = normalizeEvidenceText(value);
        if (normalized.length() <= maxLength) {
            return normalized;
        }
        return normalized.substring(0, maxLength) + "…";
    }

    private String normalizeEvidenceText(String value) {
        return normalizeEvidenceTextStatic(value);
    }

    private static String normalizeEvidenceTextStatic(String value) {
        return value == null ? "" : value.replaceAll("\\s+", " ").trim();
    }

    private static final class ChatRequestTiming {
        private final long startedAtNanos = System.nanoTime();
        private final int userQueryLength;
        private final Map<String, Long> stageMs = new LinkedHashMap<>();
        private final Map<String, Long> activeStageStarts = new HashMap<>();
        private String route = "UNKNOWN";
        private int retrievalHitCount;
        private int citationCount;
        private long lastMarkNanos = startedAtNanos;

        private ChatRequestTiming(String userMessage) {
            this.userQueryLength = userMessage == null ? 0 : userMessage.length();
        }

        static ChatRequestTiming start(String userMessage) {
            return new ChatRequestTiming(userMessage);
        }

        void route(String route) {
            this.route = route;
        }

        void mark(String stage) {
            long now = System.nanoTime();
            stageMs.merge(stage, TimeUnit.NANOSECONDS.toMillis(now - lastMarkNanos), Long::sum);
            lastMarkNanos = now;
        }

        void begin(String stage) {
            activeStageStarts.put(stage, System.nanoTime());
        }

        void end(String stage) {
            Long stageStartedAt = activeStageStarts.remove(stage);
            if (stageStartedAt != null) {
                stageMs.merge(stage, TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - stageStartedAt), Long::sum);
            }
        }

        void retrievalHitCount(int retrievalHitCount) {
            this.retrievalHitCount = Math.max(this.retrievalHitCount, retrievalHitCount);
        }

        void citationCount(int citationCount) {
            this.citationCount = citationCount;
        }

        void log(Logger logger, String conversationId, String generationId) {
            logger.info(
                    "chat timing: conversationId={}, generationId={}, route={}, userQueryLength={}, retrievalHitCount={}, citationCount={}, totalMs={}, stageMs={}",
                    conversationId,
                    generationId,
                    route,
                    userQueryLength,
                    retrievalHitCount,
                    citationCount,
                    TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startedAtNanos),
                    stageMs
            );
        }
    }

    public record ReferenceInfo(
            String paperId,
            String paperTitle,
            String originalFilename,
            Integer pageNumber,
            String anchorText,
            String retrievalMode,
            String retrievalLabel,
            String retrievalQuery,
            String matchedChunkText,
            String evidenceSnippet,
            Double score,
            Integer chunkId,
            String elementType,
            String sectionTitle,
            Integer sectionLevel,
            String bboxJson,
            String parserName,
            String parserVersion,
            String sourceKind,
            String tableId,
            String figureId,
            String formulaId,
            String evidenceRole,
            String retrievalRoute,
            String intent,
            String rankReason,
            String tableText,
            String tableMarkdown,
            Boolean tableScreenshotAvailable,
            String sourceType,
            String evidenceAssetLevel,
            Boolean pdfEvidenceAvailable,
            Boolean structuredImport,
            Boolean evalImport,
            Boolean pageScreenshotAvailable,
            Boolean figureScreenshotAvailable,
            List<String> assetWarnings
    ) {
        public ReferenceInfo {
            sourceKind = sourceKind == null || sourceKind.isBlank() ? "TEXT" : sourceKind;
            evidenceRole = evidenceRole == null || evidenceRole.isBlank() ? "NORMAL_TEXT" : evidenceRole;
            tableScreenshotAvailable = Boolean.TRUE.equals(tableScreenshotAvailable);
            sourceType = sourceType == null || sourceType.isBlank() ? "PDF" : sourceType;
            structuredImport = Boolean.TRUE.equals(structuredImport);
            evalImport = Boolean.TRUE.equals(evalImport);
            pdfEvidenceAvailable = Boolean.TRUE.equals(pdfEvidenceAvailable);
            pageScreenshotAvailable = Boolean.TRUE.equals(pageScreenshotAvailable);
            figureScreenshotAvailable = Boolean.TRUE.equals(figureScreenshotAvailable);
            evidenceAssetLevel = evidenceAssetLevel == null || evidenceAssetLevel.isBlank()
                    ? (structuredImport ? "TEXT_ONLY" : pdfEvidenceAvailable ? "PDF_VISUAL" : "PDF_PENDING_ASSETS")
                    : evidenceAssetLevel;
            assetWarnings = assetWarnings == null ? List.of() : assetWarnings.stream()
                    .filter(value -> value != null && !value.isBlank())
                    .toList();
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String figureId,
                             String formulaId,
                             String evidenceRole,
                             String retrievalRoute,
                             String intent,
                             String rankReason,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    figureId,
                    formulaId,
                    evidenceRole,
                    retrievalRoute,
                    intent,
                    rankReason,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    null,
                    null,
                    false,
                    false,
                    false,
                    false,
                    false,
                    List.of()
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    null,
                    null,
                    "NORMAL_TEXT",
                    null,
                    null,
                    null,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    null,
                    null,
                    false,
                    false,
                    false,
                    false,
                    false,
                    List.of()
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable,
                             String sourceType,
                             String evidenceAssetLevel,
                             Boolean pdfEvidenceAvailable,
                             Boolean structuredImport,
                             Boolean evalImport,
                             Boolean pageScreenshotAvailable,
                             Boolean figureScreenshotAvailable,
                             List<String> assetWarnings) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    null,
                    null,
                    "NORMAL_TEXT",
                    null,
                    null,
                    null,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    sourceType,
                    evidenceAssetLevel,
                    pdfEvidenceAvailable,
                    structuredImport,
                    evalImport,
                    pageScreenshotAvailable,
                    figureScreenshotAvailable,
                    assetWarnings
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    "TEXT",
                    null,
                    null,
                    null,
                    "NORMAL_TEXT",
                    null,
                    null,
                    null,
                    null,
                    null,
                    false,
                    null,
                    null,
                    false,
                    false,
                    false,
                    false,
                    false,
                    List.of()
            );
        }
    }

    public record ChatRequest(
            String message,
            PaperAnswerService.AnswerScope scope
    ) {
    }
}
