package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.exception.RateLimitExceededException;
import com.yizhaoqi.smartpai.model.ConversationScopeMode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentHashMap.KeySetView;
import java.util.concurrent.CancellationException;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 *
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {

    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final int MAX_EVIDENCE_SNIPPET_LEN = 160;
    private static final int MAX_PRODUCT_STATE_ITEMS = 10;
    private static final String READING_PAPER_CHOICE_KIND = "READING_PAPER_CHOICE";
    private static final String LIST_PAPERS_TOOL = "list_papers";
    private static final String SEARCH_PAPER_CANDIDATES_TOOL = "search_paper_candidates";
    private static final String FIND_PAPERS_BY_IDENTITY_TOOL = "find_papers_by_identity";
    private static final Set<String> PAPER_CHOICE_SOURCE_TOOLS = Set.of(
            LIST_PAPERS_TOOL,
            SEARCH_PAPER_CANDIDATES_TOOL,
            FIND_PAPERS_BY_IDENTITY_TOOL
    );
    private static final Pattern CITED_REFERENCE_PATTERN =
            Pattern.compile("\\[(\\d+)]");
    private static final Pattern PAPER_HANDLE_PATTERN =
            Pattern.compile("^paper_handle_[A-Za-z0-9_-]+$");
    private final RedisTemplate<String, String> redisTemplate;
    private final RateLimitService rateLimitService;
    private final ConversationService conversationService;
    private final ConversationScopeService conversationScopeService;
    private final ChatGenerationStateService chatGenerationStateService;
    private final ChatSessionRegistry chatSessionRegistry;
    private final ProductReadingConversationService productReadingConversationService;
    private final ProductPaperHandleService productPaperHandleService;
    private final ThreadPoolTaskExecutor chatMonitorExecutor;
    private final ObjectMapper objectMapper;

    // 用于存储每次生成任务的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每次生成任务的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于标记已经取消的生成任务，防止后续又被落成 completed
    private final KeySetView<String, Boolean> cancelledGenerations = ConcurrentHashMap.newKeySet();
    // 记录每次生成任务归属的前端页面实例，避免同一用户多个标签页之间串流。
    private final Map<String, String> generationClientIds = new ConcurrentHashMap<>();
    // 用于存储每次生成任务的引用映射：generationId -> {referenceNumber -> detail}
    private final Map<String, Map<Integer, ReferenceInfo>> generationReferenceMappings = new ConcurrentHashMap<>();
    private final Map<String, Map<String, Object>> generationDiagnostics = new ConcurrentHashMap<>();
    private final Map<String, List<Map<String, Object>>> generationProductStateItems = new ConcurrentHashMap<>();
    private final Map<String, Map<String, Object>> generationEffectiveScopes = new ConcurrentHashMap<>();
    private final Map<String, ChatRequestTiming> generationTimings = new ConcurrentHashMap<>();

    @Autowired
    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      RateLimitService rateLimitService,
                      ConversationService conversationService,
                      ConversationScopeService conversationScopeService,
                      ChatGenerationStateService chatGenerationStateService,
                      ChatSessionRegistry chatSessionRegistry,
                      ProductReadingConversationService productReadingConversationService,
                      ProductPaperHandleService productPaperHandleService,
                      ObjectMapper objectMapper,
                      @Qualifier("chatMonitorExecutor") ThreadPoolTaskExecutor chatMonitorExecutor) {
        this.redisTemplate = redisTemplate;
        this.rateLimitService = rateLimitService;
        this.conversationService = conversationService;
        this.conversationScopeService = conversationScopeService;
        this.chatGenerationStateService = chatGenerationStateService;
        this.chatSessionRegistry = chatSessionRegistry;
        this.productReadingConversationService = productReadingConversationService;
        this.productPaperHandleService = productPaperHandleService;
        this.objectMapper = objectMapper;
        this.chatMonitorExecutor = chatMonitorExecutor;
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        processMessage(userId, new ChatRequest(userMessage, null), session);
    }

    public void processMessage(String userId, ChatRequest request, WebSocketSession session) {
        String userMessage = request == null ? "" : request.message();
        ProductReferenceFocus incomingReferenceFocus = request == null ? null : request.referenceFocus();
        RetrievalBudgetProfile retrievalBudgetProfile = RetrievalBudgetProfile.INTERACTIVE;
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        String requestClientId = resolveClientId(session);
        String requestedConversationId = request == null ? null : trimToNull(request.conversationId());
        String conversationId = null;
        String generationId = null;
        try {
            rateLimitService.checkChatByUser(userId);

            Long userIdLong = Long.parseLong(userId);
            if (requestedConversationId == null) {
                conversationId = getOrCreateConversationId(userId);
                conversationService.ensureConversationSession(userIdLong, conversationId, userMessage);
            } else {
                conversationId = requestedConversationId;
                conversationService.requireActiveOwnedConversationSession(userIdLong, conversationId);
            }
            ConversationScopeService.EffectiveConversationScope resolvedScope =
                    conversationScopeService.resolveForChat(userIdLong, conversationId);
            String clickedSourceQuoteRef = structuredSourceQuoteRef(incomingReferenceFocus);
            ProductReferenceFocus referenceFocus =
                    resolveReferenceFocus(
                            userIdLong,
                            conversationId,
                            referenceFocus(incomingReferenceFocus)
                    );
            if (referenceFocus != null) {
                conversationScopeService.assertReferenceFocusWithinScope(resolvedScope, referenceFocus);
            }
            ChatGenerationStateService.GenerationSnapshot generation =
                    chatGenerationStateService.createGeneration(userId, requestClientId, conversationId, userMessage);
            generationId = generation.generationId();
            ConversationScopeService.EffectiveConversationScope effectiveScope =
                    conversationScopeService.lockForFirstMessage(userIdLong, conversationId);
            if (referenceFocus != null) {
                conversationScopeService.assertReferenceFocusWithinScope(effectiveScope, referenceFocus);
            }
            SourceScope productScope = productSourceScope(effectiveScope, retrievalBudgetProfile);
            List<String> clickedPaperHandles = clickedPaperHandles(referenceFocus);
            Map<String, Object> effectiveScopeMap = effectiveScopeMap(
                    effectiveScope,
                    clickedSourceQuoteRef,
                    true,
                    clickedPaperHandles,
                    referenceFocus == null ? null : referenceFocus.readingAction()
            );
            final String finalConversationId = conversationId;
            final String finalGenerationId = generationId;
            generationClientIds.put(finalGenerationId, requestClientId);
            generationEffectiveScopes.put(finalGenerationId, effectiveScopeMap);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            sendGenerationStart(userId, finalGenerationId, finalConversationId);
            ChatRequestTiming timing = ChatRequestTiming.start(userMessage);
                generationTimings.put(finalGenerationId, timing);

            // 为当前生成任务创建响应构建器
            responseBuilders.put(finalGenerationId, new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(finalGenerationId, responseFuture);

            timing.route("PRODUCT_READING_REACT");
            timing.mark("intent_route_decided");

            // 2. 异步执行 Product Reading ReAct Harness；产品语义由 Harness 和产品工具目录处理。
            try {
                chatMonitorExecutor.execute(() ->
                        runReadingHarnessSafely(userId, userMessage, finalConversationId, finalGenerationId, productScope, responseFuture));
            } catch (RejectedExecutionException ex) {
                logger.warn("聊天处理线程池已满，generationId: {}", finalGenerationId);
                RuntimeException busyException = new RuntimeException("系统繁忙，请稍后重试");
                chatGenerationStateService.markFailed(finalGenerationId, busyException.getMessage());
                handleError(userId, requestClientId, finalGenerationId, busyException);
                sendCompletionNotification(userId, finalGenerationId, finalConversationId, true, false);
                cleanupGenerationState(finalGenerationId, ex);
            }

        } catch (RateLimitExceededException e) {
            sendRateLimitMessage(userId, requestClientId, null, e);
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            if (generationId != null) {
                chatGenerationStateService.markFailed(generationId, e.getMessage());
                cleanupGenerationState(generationId, e);
            }
            handleError(userId, requestClientId, generationId, e);
        }
    }

    private SourceScope productSourceScope(ConversationScopeService.EffectiveConversationScope effectiveScope,
                                           RetrievalBudgetProfile retrievalBudgetProfile) {
        if (effectiveScope != null && effectiveScope.mode() == ConversationScopeMode.SOURCE_SET_SNAPSHOT) {
            return SourceScope.manual(effectiveScope.paperIds(), retrievalBudgetProfile);
        }
        return SourceScope.auto(retrievalBudgetProfile);
    }

    private ProductReferenceFocus referenceFocus(ProductReferenceFocus incomingScope) {
        if (hasReferenceFocus(incomingScope)) {
            return structuredReferenceFocus(incomingScope);
        }
        return null;
    }

    private ProductReferenceFocus structuredReferenceFocus(ProductReferenceFocus incomingScope) {
        String focusPaperId = trimToNull(incomingScope.paperId());
        List<String> focusPaperIds = focusPaperId == null
                ? incomingScope.paperIds()
                : List.of(focusPaperId);
        String focusPaperTitle = trimToNull(incomingScope.paperTitle());
        List<String> focusPaperTitles = focusPaperTitle == null
                ? incomingScope.paperTitles()
                : List.of(focusPaperTitle);
        String focusPaperHandle = trimToNull(incomingScope.paperHandle());
        List<String> focusPaperHandles = focusPaperHandle == null
                ? incomingScope.paperHandles()
                : List.of(focusPaperHandle);
        return new ProductReferenceFocus(
                focusPaperIds,
                focusPaperTitles,
                incomingScope.referenceNumber(),
                incomingScope.conversationRecordId(),
                incomingScope.chunkId(),
                incomingScope.pageNumber(),
                incomingScope.paperId(),
                incomingScope.paperTitle(),
                incomingScope.originalFilename(),
                incomingScope.matchedText(),
                incomingScope.bboxJson(),
                incomingScope.sourceKind(),
                incomingScope.sourceQuoteRef(),
                focusPaperHandles,
                incomingScope.paperHandle(),
                incomingScope.readingAction()
        );
    }

    private String structuredSourceQuoteRef(ProductReferenceFocus incomingScope) {
        if (incomingScope == null) {
            return null;
        }
        return incomingScope.sourceQuoteRef();
    }

    private ProductReferenceFocus resolveReferenceFocus(
            Long userId,
            String conversationId,
            ProductReferenceFocus referenceFocus) {
        if (referenceFocus == null) {
            return referenceFocus;
        }
        if (referenceFocus.sourceQuoteRef() != null) {
            return referenceFocus;
        }
        if (referenceFocus.referenceNumber() == null) {
            return referenceFocus;
        }

        Optional<Map<String, Object>> detail = referenceFocus.conversationRecordId() == null
                ? conversationService.findLatestReferenceDetail(userId, conversationId, referenceFocus.referenceNumber())
                : conversationService.findReferenceDetail(userId, referenceFocus.conversationRecordId(), referenceFocus.referenceNumber());
        Map<String, Object> resolvedDetail = detail.orElseThrow(() ->
                new IllegalArgumentException("Reference focus could not be resolved to a paper"));
        String paperId = stringDetail(resolvedDetail, "paperId");
        if (paperId == null) {
            throw new IllegalArgumentException("Reference focus could not be resolved to a paper");
        }
        return enrichReferenceFocus(referenceFocus, resolvedDetail, paperId);
    }

    private ProductReferenceFocus enrichReferenceFocus(
            ProductReferenceFocus referenceFocus,
            Map<String, Object> detail,
            String paperId) {
        String paperTitle = firstNonBlank(stringDetail(detail, "paperTitle"), referenceFocus.paperTitle());
        String originalFilename = firstNonBlank(stringDetail(detail, "originalFilename"), referenceFocus.originalFilename());
        String matchedText = firstNonBlank(
                stringDetail(detail, "matchedChunkText"),
                stringDetail(detail, "evidenceSnippet"),
                stringDetail(detail, "anchorText"),
                stringDetail(detail, "matchedText"),
                referenceFocus.matchedText()
        );
        return new ProductReferenceFocus(
                List.of(paperId),
                paperTitle == null ? referenceFocus.paperTitles() : List.of(paperTitle),
                referenceFocus.referenceNumber(),
                referenceFocus.conversationRecordId(),
                firstNonNull(integerDetail(detail, "chunkId"), referenceFocus.chunkId()),
                firstNonNull(integerDetail(detail, "pageNumber"), referenceFocus.pageNumber()),
                paperId,
                paperTitle,
                originalFilename,
                matchedText,
                firstNonBlank(stringDetail(detail, "bboxJson"), referenceFocus.bboxJson()),
                firstNonBlank(stringDetail(detail, "sourceKind"), referenceFocus.sourceKind()),
                firstNonBlank(stringDetail(detail, "sourceQuoteRef"), referenceFocus.sourceQuoteRef()),
                referenceFocus.paperHandles(),
                referenceFocus.paperHandle(),
                referenceFocus.readingAction()
        );
    }

    private String stringDetail(Map<String, Object> detail, String key) {
        if (detail == null) {
            return null;
        }
        Object value = detail.get(key);
        return value == null ? null : trimToNull(String.valueOf(value));
    }

    private Integer integerDetail(Map<String, Object> detail, String key) {
        if (detail == null) {
            return null;
        }
        Object value = detail.get(key);
        if (value instanceof Number number) {
            return number.intValue();
        }
        String text = value == null ? null : trimToNull(String.valueOf(value));
        if (text == null) {
            return null;
        }
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    private Double doubleDetail(Map<String, Object> detail, String key) {
        if (detail == null) {
            return null;
        }
        Object value = detail.get(key);
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        String text = value == null ? null : trimToNull(String.valueOf(value));
        if (text == null) {
            return null;
        }
        try {
            return Double.parseDouble(text);
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    private Boolean booleanDetail(Map<String, Object> detail, String key) {
        if (detail == null) {
            return false;
        }
        Object value = detail.get(key);
        if (value instanceof Boolean bool) {
            return bool;
        }
        String text = value == null ? null : trimToNull(String.valueOf(value));
        return text != null && Boolean.parseBoolean(text);
    }

    @SafeVarargs
    private final <T> T firstNonNull(T... values) {
        if (values == null) {
            return null;
        }
        for (T value : values) {
            if (value != null) {
                return value;
            }
        }
        return null;
    }

    private String firstNonBlank(String... values) {
        if (values == null) {
            return null;
        }
        for (String value : values) {
            String trimmed = trimToNull(value);
            if (trimmed != null) {
                return trimmed;
            }
        }
        return null;
    }

    private boolean hasReferenceFocus(ProductReferenceFocus scope) {
        if (scope == null) {
            return false;
        }
        if (scope.referenceNumber() != null || scope.sourceQuoteRef() != null) {
            return true;
        }
        return scope.paperHandle() != null
                || !scope.paperHandles().isEmpty()
                || scope.paperId() != null
                || !scope.paperIds().isEmpty()
                || scope.readingAction() != null;
    }

    private Map<String, Object> effectiveScopeMap(ConversationScopeService.EffectiveConversationScope effectiveScope) {
        return effectiveScopeMap(effectiveScope, null, false, List.of());
    }

    private Map<String, Object> effectiveScopeMap(ConversationScopeService.EffectiveConversationScope effectiveScope,
                                                  String clickedSourceQuoteRef,
                                                  boolean includeClickedSourceQuoteRef) {
        return effectiveScopeMap(effectiveScope, clickedSourceQuoteRef, includeClickedSourceQuoteRef, List.of());
    }

    private Map<String, Object> effectiveScopeMap(ConversationScopeService.EffectiveConversationScope effectiveScope,
                                                  String clickedSourceQuoteRef,
                                                  boolean includeClickedSourceQuoteRef,
                                                  List<String> clickedPaperHandles) {
        return effectiveScopeMap(effectiveScope, clickedSourceQuoteRef, includeClickedSourceQuoteRef, clickedPaperHandles, null);
    }

    private Map<String, Object> effectiveScopeMap(ConversationScopeService.EffectiveConversationScope effectiveScope,
                                                  String clickedSourceQuoteRef,
                                                  boolean includeClickedSourceQuoteRef,
                                                  List<String> clickedPaperHandles,
                                                  String readingAction) {
        ConversationScopeMode mode = effectiveScope == null ? ConversationScopeMode.AUTO_LIBRARY : effectiveScope.mode();
        List<String> paperIds = effectiveScope == null ? List.of() : effectiveScope.paperIds();
        Map<String, Object> scope = new LinkedHashMap<>();
        scope.put("scopeMode", mode.name());
        scope.put("sourceLabel", effectiveScope == null
                ? ConversationScopeService.DEFAULT_AUTO_LIBRARY_LABEL
                : effectiveScope.label());
        scope.put("paperIds", paperIds);
        scope.put("paperCount", mode == ConversationScopeMode.SOURCE_SET_SNAPSHOT ? paperIds.size() : 0);
        if (includeClickedSourceQuoteRef && clickedSourceQuoteRef != null) {
            scope.put("clickedSourceQuoteRefs", List.of(clickedSourceQuoteRef));
        }
        if (includeClickedSourceQuoteRef && clickedPaperHandles != null && !clickedPaperHandles.isEmpty()) {
            scope.put("clickedPaperHandles", clickedPaperHandles);
        }
        String safeReadingAction = trimToNull(readingAction);
        if (includeClickedSourceQuoteRef && safeReadingAction != null) {
            scope.put("readingAction", safeReadingAction);
        }
        return scope;
    }

    private List<String> clickedPaperHandles(ProductReferenceFocus referenceFocus) {
        if (referenceFocus == null) {
            return List.of();
        }
        LinkedHashMap<String, Boolean> handles = new LinkedHashMap<>();
        for (String paperHandle : referenceFocus.paperHandles()) {
            String trimmed = trimToNull(paperHandle);
            if (trimmed != null) {
                handles.put(trimmed, true);
            }
        }
        if (!handles.isEmpty()) {
            return List.copyOf(handles.keySet());
        }
        if (productPaperHandleService == null) {
            return List.of();
        }
        LinkedHashMap<String, Boolean> paperIds = new LinkedHashMap<>();
        for (String paperId : referenceFocus.paperIds()) {
            String trimmed = trimToNull(paperId);
            if (trimmed != null) {
                paperIds.put(trimmed, true);
            }
        }
        String singlePaperId = trimToNull(referenceFocus.paperId());
        if (singlePaperId != null) {
            paperIds.put(singlePaperId, true);
        }
        for (String paperId : paperIds.keySet()) {
            String paperHandle = trimToNull(productPaperHandleService.handleForPaperId(paperId));
            if (paperHandle != null) {
                handles.put(paperHandle, true);
            }
        }
        return List.copyOf(handles.keySet());
    }

    private void runReadingHarnessSafely(String userId,
                                         String userMessage,
                                         String conversationId,
                                         String generationId,
                                         SourceScope scope,
                                         CompletableFuture<String> responseFuture) {
        try {
            runReadingHarness(userId, userMessage, conversationId, generationId, scope, responseFuture);
        } catch (Exception e) {
            logger.error("Product Reading ReAct Harness 执行失败: generationId={}", generationId, e);
            chatGenerationStateService.markFailed(generationId, e.getMessage());
            handleError(userId, generationId, e);
            sendCompletionNotification(userId, generationId, conversationId, true, false);
            cleanupGenerationState(generationId, e);
        }
    }

    private void runReadingHarness(String userId,
                                   String userMessage,
                                   String conversationId,
                                   String generationId,
                                   SourceScope scope,
                                   CompletableFuture<String> responseFuture) {
        if (productReadingConversationService == null) {
            throw new IllegalStateException("ProductReadingConversationService is required for reading chat");
        }
        ChatRequestTiming timing = generationTimings.get(generationId);
        if (timing != null) {
            timing.begin("product_reading_react_harness");
        }
        Map<String, Object> effectiveScope = generationEffectiveScopes.get(generationId);
        ProductTurnResult answer = productReadingConversationService.runTurn(
                Long.parseLong(userId),
                conversationId,
                generationId,
                userMessage,
                scope,
                ProductModelContext.defaults(),
                effectiveScope,
                event -> sendProductToolCall(userId, generationId, conversationId, event)
        );
        if (timing != null) {
            timing.end("product_reading_react_harness");
            timing.route(answer.envelope() == null ? answer.stopReason().name() : answer.envelope().answerType().name());
            timing.retrievalHitCount(answer.references().size());
        }
        Map<String, Object> diagnostics = productDiagnostics(answer);
        if (!diagnostics.isEmpty()) {
            diagnostics.put("harness", "PRODUCT_READING_REACT");
            generationDiagnostics.put(generationId, diagnostics);
            chatGenerationStateService.updateDiagnostics(generationId, diagnostics);
        }
        if (answer.resultStatus() == ProductResultStatus.FAILED) {
            throw new RuntimeException(answer.finalAnswerMarkdown());
        }
        List<Map<String, Object>> productStateItems = sanitizeProductStateItems(answer.productStateItems());
        if (!productStateItems.isEmpty()) {
            generationProductStateItems.put(generationId, productStateItems);
        }
        Map<Integer, ReferenceInfo> productReferences = productReferenceMappings(answer.references());
        Map<String, Map<String, Object>> serializableReferences = toSerializableReferenceMappings(productReferences);
        if (!productReferences.isEmpty()) {
            generationReferenceMappings.put(generationId, productReferences);
            chatGenerationStateService.updateReferenceMappings(generationId, serializableReferences);
        }
        conversationService.recordConversation(
                Long.parseLong(userId),
                userMessage,
                answer.finalAnswerMarkdown(),
                conversationId,
                serializableReferences,
                effectiveScope == null ? Map.of() : effectiveScope
        );
        appendStreamChunk(userId, generationId, conversationId, answer.finalAnswerMarkdown());
        finalizeResponse(
                userId,
                userMessage,
                conversationId,
                generationId,
                responseFuture,
                responseBuilders.get(generationId),
                new LlmProviderRouter.StreamCompletion(
                        answer.stopReason().name(),
                        0,
                        0,
                        answer.finalAnswerMarkdown().length()
                )
        );
    }

    private Map<String, Object> productDiagnostics(ProductTurnResult answer) {
        if (answer == null) {
            return Map.of();
        }
        Map<String, Object> diagnostics = new LinkedHashMap<>();
        diagnostics.put("harness", "PRODUCT_READING_REACT");
        diagnostics.put("resultStatus", answer.resultStatus().name());
        diagnostics.put("stopReason", answer.stopReason().name());
        if (answer.envelope() != null) {
            diagnostics.put("answerType", answer.envelope().answerType().name());
        }
        diagnostics.put("referenceCount", answer.references().size());
        return diagnostics;
    }

    private Map<Integer, ReferenceInfo> productReferenceMappings(List<Map<String, Object>> references) {
        Map<Integer, ReferenceInfo> mappings = new LinkedHashMap<>();
        int fallbackNumber = 1;
        for (Map<String, Object> reference : references == null ? List.<Map<String, Object>>of() : references) {
            Integer referenceNumber = integerDetail(reference, "referenceNumber");
            if (referenceNumber == null || referenceNumber <= 0) {
                referenceNumber = fallbackNumber;
            }
            fallbackNumber = Math.max(fallbackNumber + 1, referenceNumber + 1);
            mappings.put(referenceNumber, referenceInfoFromProductReference(enrichProductReference(reference)));
        }
        return mappings;
    }

    private Map<String, Object> enrichProductReference(Map<String, Object> reference) {
        if (reference == null || reference.isEmpty()) {
            return Map.of();
        }
        Map<String, Object> enriched = new LinkedHashMap<>(reference);
        if (stringDetail(enriched, "paperId") == null) {
            String paperHandle = stringDetail(enriched, "paperHandle");
            if (paperHandle != null) {
                productPaperHandleService.resolvePaperHandle(paperHandle)
                        .ifPresent(paperId -> enriched.put("paperId", paperId));
            }
        }
        return enriched;
    }

    private List<Map<String, Object>> sanitizeProductStateItems(List<Map<String, Object>> rawItems) {
        if (rawItems == null || rawItems.isEmpty()) {
            return List.of();
        }
        List<Map<String, Object>> items = new ArrayList<>();
        Map<String, Boolean> seenHandles = new LinkedHashMap<>();
        for (Map<String, Object> rawItem : rawItems) {
            if (items.size() >= MAX_PRODUCT_STATE_ITEMS) {
                break;
            }
            Map<String, Object> item = sanitizeReadingPaperChoiceItem(rawItem);
            if (item.isEmpty()) {
                continue;
            }
            String paperHandle = String.valueOf(item.get("paperHandle"));
            if (seenHandles.putIfAbsent(paperHandle, true) != null) {
                continue;
            }
            items.add(item);
        }
        return List.copyOf(items);
    }

    private Map<String, Object> sanitizeReadingPaperChoiceItem(Map<String, Object> rawItem) {
        if (rawItem == null
                || !READING_PAPER_CHOICE_KIND.equals(rawItem.get("kind"))) {
            return Map.of();
        }
        String sourceTool = trimToNull(String.valueOf(rawItem.get("sourceTool")));
        if (sourceTool == null || !PAPER_CHOICE_SOURCE_TOOLS.contains(sourceTool)) {
            return Map.of();
        }
        String paperHandle = trimToNull(String.valueOf(rawItem.get("paperHandle")));
        if (paperHandle == null || !PAPER_HANDLE_PATTERN.matcher(paperHandle).matches()) {
            return Map.of();
        }
        Map<String, Object> item = new LinkedHashMap<>();
        item.put("kind", READING_PAPER_CHOICE_KIND);
        item.put("sourceTool", sourceTool);
        item.put("paperHandle", paperHandle);
        copyStringDetail(item, rawItem, "title");
        copyStringDetail(item, rawItem, "originalFilename");
        copyStringListDetail(item, rawItem, "authors");
        copyNumberDetail(item, rawItem, "year");
        copyStringDetail(item, rawItem, "venue");
        if (FIND_PAPERS_BY_IDENTITY_TOOL.equals(sourceTool)) {
            copyStringListDetail(item, rawItem, "matchReasons");
            copyStringDetail(item, rawItem, "identityStatus");
            Object ambiguous = rawItem.get("ambiguous");
            if (ambiguous instanceof Boolean booleanValue) {
                item.put("ambiguous", booleanValue);
            }
        }
        return item;
    }

    private void copyStringDetail(Map<String, Object> target, Map<String, Object> source, String key) {
        String value = stringDetail(source, key);
        if (value != null) {
            target.put(key, value);
        }
    }

    private void copyStringListDetail(Map<String, Object> target, Map<String, Object> source, String key) {
        List<String> values = stringListValue(source.get(key));
        if (!values.isEmpty()) {
            target.put(key, values);
        }
    }

    private void copyNumberDetail(Map<String, Object> target, Map<String, Object> source, String key) {
        Object value = source.get(key);
        if (value instanceof Number number) {
            target.put(key, number);
        }
    }

    private ReferenceInfo referenceInfoFromProductReference(Map<String, Object> reference) {
        String sourceQuoteContent = stringDetail(reference, "content");
        String matchedText = firstNonBlank(
                stringDetail(reference, "matchedChunkText"),
                stringDetail(reference, "matchedText"),
                sourceQuoteContent,
                stringDetail(reference, "snippet"),
                stringDetail(reference, "evidenceSnippet")
        );
        String evidenceSnippet = firstNonBlank(
                stringDetail(reference, "evidenceSnippet"),
                stringDetail(reference, "snippet"),
                sourceQuoteContent,
                trimToMaxLength(matchedText, MAX_EVIDENCE_SNIPPET_LEN)
        );
        return new ReferenceInfo(
                stringDetail(reference, "paperId"),
                firstNonBlank(stringDetail(reference, "paperTitle"), stringDetail(reference, "title")),
                stringDetail(reference, "originalFilename"),
                integerDetail(reference, "pageNumber"),
                firstNonBlank(stringDetail(reference, "anchorText"), sourceQuoteContent, matchedText),
                firstNonBlank(stringDetail(reference, "retrievalMode"), "PRODUCT_READING_REACT"),
                firstNonBlank(stringDetail(reference, "retrievalLabel"), "Product Reading evidence"),
                firstNonBlank(stringDetail(reference, "retrievalQuery"), stringDetail(reference, "question")),
                matchedText,
                evidenceSnippet,
                doubleDetail(reference, "score"),
                integerDetail(reference, "chunkId"),
                stringDetail(reference, "elementType"),
                stringDetail(reference, "sectionTitle"),
                integerDetail(reference, "sectionLevel"),
                stringDetail(reference, "bboxJson"),
                stringDetail(reference, "parserName"),
                stringDetail(reference, "parserVersion"),
                stringDetail(reference, "sourceKind"),
                stringDetail(reference, "tableId"),
                stringDetail(reference, "figureId"),
                stringDetail(reference, "formulaId"),
                stringDetail(reference, "evidenceRole"),
                firstNonBlank(stringDetail(reference, "retrievalRoute"), "PRODUCT_READING_REACT"),
                stringDetail(reference, "intent"),
                stringDetail(reference, "rankReason"),
                stringDetail(reference, "tableText"),
                stringDetail(reference, "tableMarkdown"),
                booleanDetail(reference, "tableScreenshotAvailable"),
                "PDF",
                firstNonBlank(stringDetail(reference, "evidenceAssetLevel"), stringDetail(reference, "assetLevel")),
                booleanDetail(reference, "pdfEvidenceAvailable"),
                booleanDetail(reference, "pageScreenshotAvailable"),
                booleanDetail(reference, "figureScreenshotAvailable"),
                stringDetail(reference, "citationRef"),
                stringDetail(reference, "evidenceRef"),
                stringDetail(reference, "sourceQuoteRef"),
                stringListValue(reference.get("assetWarnings"))
        );
    }

    private String trimToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private String resolveClientId(WebSocketSession session) {
        String clientId = chatSessionRegistry.getClientId(session);
        if (clientId != null && !clientId.isBlank()) {
            return clientId;
        }
        return session != null ? session.getId() : null;
    }

    private void appendStreamChunk(String userId, String generationId, String conversationId, String chunk) {
        if (chunk == null || chunk.isEmpty() || isGenerationCancelled(generationId)) {
            return;
        }
        StringBuilder responseBuilder = responseBuilders.get(generationId);
        if (responseBuilder != null) {
            responseBuilder.append(chunk);
        }
        chatGenerationStateService.appendChunk(generationId, chunk);
        sendResponseChunk(userId, generationId, conversationId, chunk);
    }

    private void finalizeResponse(String userId, String userMessage, String conversationId, String generationId,
                                  CompletableFuture<String> responseFuture,
                                  StringBuilder responseBuilder,
                                  LlmProviderRouter.StreamCompletion completion) {
        if (finishCancelledGeneration(generationId, responseFuture, responseBuilder)) {
            return;
        }
        if (responseBuilder == null) {
            if (responseFuture.isDone() || !responseFutures.containsKey(generationId)) {
                return;
            }
            RuntimeException exception = new RuntimeException("响应构建器为空");
            if (responseFuture.completeExceptionally(exception)) {
                handleError(userId, generationId, exception);
                sendCompletionNotification(userId, generationId, conversationId, true, false);
                chatGenerationStateService.markFailed(generationId, exception.getMessage());
                cleanupGenerationState(generationId, exception);
            }
            return;
        }
        String completeResponse = responseBuilder.toString();
        if (completeResponse.isBlank()) {
            RuntimeException exception = new RuntimeException("模型未返回有效内容，请稍后重试");
            if (responseFuture.completeExceptionally(exception)) {
                handleError(userId, generationId, exception);
                sendCompletionNotification(userId, generationId, conversationId, true, false);
                chatGenerationStateService.markFailed(generationId, exception.getMessage());
                cleanupGenerationState(generationId, exception);
            }
            return;
        }
        if (!responseFuture.complete(completeResponse)) {
            return;
        }
        logger.info("模型回答收尾: generationId={}, conversationId={}, answerChars={}, finishReason={}, promptTokens={}, completionTokens={}",
                generationId,
                conversationId,
                completeResponse.length(),
                completion != null && completion.finishReason() != null ? completion.finishReason() : "unknown",
                completion != null ? completion.promptTokens() : 0,
                completion != null ? completion.completionTokens() : 0);
        Map<Integer, ReferenceInfo> referenceMappings = filterReferenceMappingsForResponse(
                generationReferenceMappings.get(generationId),
                completeResponse
        );
        if (referenceMappings.isEmpty()) {
            generationReferenceMappings.remove(generationId);
        } else {
            generationReferenceMappings.put(generationId, referenceMappings);
        }
        ChatRequestTiming timing = generationTimings.get(generationId);
        if (timing != null) {
            timing.citationCount(referenceMappings.size());
            timing.mark("reference_mapping_saved");
        }
        updateConversationHistory(
                conversationId,
                userMessage,
                completeResponse,
                referenceMappings,
                generationEffectiveScopes.get(generationId)
        );
        chatGenerationStateService.markCompleted(generationId, toSerializableReferenceMappings(referenceMappings));
        sendCompletionNotification(userId, generationId, conversationId, false, false);
        if (timing != null) {
            timing.mark("response_sent");
            timing.log(logger, conversationId, generationId);
        }
        logger.info("对话存储信息 - Redis键: {}, 值: {}", "user:" + userId + ":current_conversation", conversationId);
        cleanupGenerationState(generationId, null);
        logger.info("消息处理完成，用户ID: {}", userId);
    }

    private void cleanupGenerationState(String generationId, Throwable throwable) {
        responseBuilders.remove(generationId);
        generationClientIds.remove(generationId);
        generationReferenceMappings.remove(generationId);
        generationDiagnostics.remove(generationId);
        generationProductStateItems.remove(generationId);
        generationEffectiveScopes.remove(generationId);
        generationTimings.remove(generationId);
        stopFlags.remove(generationId);
        cancelledGenerations.remove(generationId);
        CompletableFuture<String> future = responseFutures.remove(generationId);
        if (throwable != null && future != null && !future.isDone()) {
            future.completeExceptionally(throwable);
        }
    }

    private boolean finishCancelledGeneration(String generationId,
                                              CompletableFuture<String> responseFuture,
                                              StringBuilder responseBuilder) {
        if (!isGenerationCancelled(generationId)) {
            return false;
        }

        if (!responseFuture.isDone()) {
            responseFuture.complete(responseBuilder != null ? responseBuilder.toString() : "");
        }
        cleanupGenerationState(generationId, null);
        logger.info("生成任务已取消并停止后续收尾逻辑: generationId={}", generationId);
        return true;
    }

    private boolean isGenerationCancelled(String generationId) {
        return generationId != null && (cancelledGenerations.contains(generationId) || Boolean.TRUE.equals(stopFlags.get(generationId)));
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);

        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }

        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        List<Map<String, Object>> records = getConversationHistoryRecords(conversationId);
        List<Map<String, String>> history = new ArrayList<>();
        for (Map<String, Object> message : records) {
            Map<String, String> normalized = new HashMap<>();
            normalized.put("role", String.valueOf(message.getOrDefault("role", "")));
            normalized.put("content", String.valueOf(message.getOrDefault("content", "")));
            Object timestamp = message.get("timestamp");
            if (timestamp != null) {
                normalized.put("timestamp", String.valueOf(timestamp));
            }
            history.add(normalized);
        }
        return history;
    }

    private String buildRecentFeedbackGuidance(String userId) {
        if (userId == null || userId.isBlank()) {
            return "";
        }
        try {
            Map<Object, Object> feedbackEntries = redisTemplate.opsForHash().entries("feedback:" + userId);
            if (feedbackEntries == null || feedbackEntries.isEmpty()) {
                return "";
            }

            StringBuilder guidance = new StringBuilder("近期用户对回答的显式反馈如下，按时间倒序排列，越靠前越新。")
                    .append("后续回答需要参考这些偏好：good 表示用户认可这类回答方式，bad 表示需要避免类似问题；")
                    .append("如果同一轮回答既有 good 又有 bad，以最新一条为准。\n");
            feedbackEntries.entrySet().stream()
                    .sorted(Comparator.comparingLong(entry -> -parseFeedbackTimestamp(entry.getKey())))
                    .limit(5)
                    .forEach(entry -> guidance.append("- ")
                            .append("feedbackTime=")
                            .append(entry.getKey())
                            .append("; ")
                            .append(entry.getValue())
                            .append("\n"));
            return guidance.toString().trim();
        } catch (Exception exception) {
            logger.warn("读取用户反馈上下文失败: userId={}", userId, exception);
            return "";
        }
    }

    private long parseFeedbackTimestamp(Object value) {
        if (value == null) {
            return 0L;
        }
        try {
            return Long.parseLong(String.valueOf(value));
        } catch (NumberFormatException exception) {
            return 0L;
        }
    }

    private List<Map<String, Object>> getConversationHistoryRecords(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }

            List<Map<String, Object>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, Object>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response,
                                           Map<Integer, ReferenceInfo> referenceMapping,
                                           Map<String, Object> effectiveScope) {
        String key = "conversation:" + conversationId;
        List<Map<String, Object>> history = getConversationHistoryRecords(conversationId);

        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));

        // 添加用户消息（带时间戳）
        Map<String, Object> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        if (effectiveScope != null && !effectiveScope.isEmpty()) {
            userMsgMap.put("effectiveScope", effectiveScope);
        }
        history.add(userMsgMap);

        // 添加助手回复（带时间戳）
        Map<String, Object> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        if (referenceMapping != null && !referenceMapping.isEmpty()) {
            assistantMsgMap.put("referenceMappings", toSerializableReferenceMappings(referenceMapping));
        }
        history.add(assistantMsgMap);

        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }

        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private Map<String, Map<String, Object>> toSerializableReferenceMappings(Map<Integer, ReferenceInfo> referenceMapping) {
        Map<String, Map<String, Object>> serialized = new HashMap<>();
        if (referenceMapping == null || referenceMapping.isEmpty()) {
            return serialized;
        }
        for (Map.Entry<Integer, ReferenceInfo> entry : referenceMapping.entrySet()) {
            ReferenceInfo detail = entry.getValue();
            Map<String, Object> item = new HashMap<>();
            item.put("paperId", detail.paperId());
            item.put("paperTitle", detail.paperTitle());
            item.put("originalFilename", detail.originalFilename());
            item.put("pageNumber", detail.pageNumber());
            item.put("anchorText", detail.anchorText());
            item.put("retrievalMode", detail.retrievalMode());
            item.put("retrievalLabel", detail.retrievalLabel());
            item.put("retrievalQuery", detail.retrievalQuery());
            item.put("matchedChunkText", detail.matchedChunkText());
            item.put("evidenceSnippet", detail.evidenceSnippet());
            item.put("score", detail.score());
            item.put("chunkId", detail.chunkId());
            item.put("elementType", detail.elementType());
            item.put("sectionTitle", detail.sectionTitle());
            item.put("sectionLevel", detail.sectionLevel());
            item.put("bboxJson", detail.bboxJson());
            item.put("parserName", detail.parserName());
            item.put("parserVersion", detail.parserVersion());
            item.put("sourceKind", detail.sourceKind());
            item.put("tableId", detail.tableId());
            item.put("figureId", detail.figureId());
            item.put("formulaId", detail.formulaId());
            item.put("evidenceRole", detail.evidenceRole());
            item.put("retrievalRoute", detail.retrievalRoute());
            item.put("intent", detail.intent());
            item.put("rankReason", detail.rankReason());
            item.put("tableText", detail.tableText());
            item.put("tableMarkdown", detail.tableMarkdown());
            item.put("tableScreenshotAvailable", detail.tableScreenshotAvailable());
            item.put("sourceType", detail.sourceType());
            item.put("evidenceAssetLevel", detail.evidenceAssetLevel());
            item.put("pdfEvidenceAvailable", detail.pdfEvidenceAvailable());
            item.put("pageScreenshotAvailable", detail.pageScreenshotAvailable());
            item.put("figureScreenshotAvailable", detail.figureScreenshotAvailable());
            item.put("citationRef", detail.citationRef());
            item.put("evidenceRef", detail.evidenceRef());
            item.put("sourceQuoteRef", detail.sourceQuoteRef());
            item.put("assetWarnings", detail.assetWarnings());
            serialized.put(String.valueOf(entry.getKey()), item);
        }
        return serialized;
    }

    static Map<Integer, ReferenceInfo> filterReferenceMappingsForResponse(Map<Integer, ReferenceInfo> referenceMapping,
                                                                          String response) {
        Map<Integer, ReferenceInfo> filtered = new LinkedHashMap<>();
        if (referenceMapping == null || referenceMapping.isEmpty() || response == null || response.isBlank()) {
            return filtered;
        }

        Matcher matcher = CITED_REFERENCE_PATTERN.matcher(response);
        while (matcher.find()) {
            try {
                Integer referenceNumber = Integer.parseInt(matcher.group(1));
                ReferenceInfo detail = referenceMapping.get(referenceNumber);
                if (detail != null) {
                    filtered.putIfAbsent(referenceNumber, detail);
                }
            } catch (NumberFormatException ignored) {
                // The regex only captures digits; keep this branch defensive for future pattern changes.
            }
        }
        return filtered;
    }

    private void sendGenerationStart(String userId, String generationId, String conversationId) {
        sendJsonToGenerationClient(userId, generationId, Map.of(
                "type", "start",
                "generationId", generationId,
                "conversationId", conversationId,
                "timestamp", System.currentTimeMillis()
        ));
    }

    private void sendResponseChunk(String userId, String generationId, String conversationId, String chunk) {
        if (Boolean.TRUE.equals(stopFlags.get(generationId))) {
            logger.debug("检测到停止标志，跳过发送响应块: generationId={}", generationId);
            return;
        }

        sendJsonToGenerationClient(userId, generationId, Map.of(
                "type", "chunk",
                "generationId", generationId,
                "conversationId", conversationId,
                "chunk", chunk
        ));
    }

    private void sendProductToolCall(String userId,
                                     String generationId,
                                     String conversationId,
                                     ToolProgressEvent event) {
        Map<String, Object> payload = new HashMap<>();
        payload.put("type", "calling_tool");
        payload.put("toolName", event.toolName());
        payload.put("generationId", generationId);
        payload.put("conversationId", conversationId);
        payload.put("timestamp", System.currentTimeMillis());
        sendJsonToGenerationClient(userId, generationId, payload);
    }

    private void sendCompletionNotification(String userId,
                                            String generationId,
                                            String conversationId,
                                            boolean failed,
                                            boolean persistenceDegraded) {
        Map<String, Object> notification = new HashMap<>();
        notification.put("type", "completion");
        notification.put("generationId", generationId);
        notification.put("conversationId", conversationId);
        notification.put("status", failed ? "failed" : "finished");
        notification.put("message", failed ? "响应已中断" : "响应已完成");
        notification.put("timestamp", System.currentTimeMillis());
        notification.put("date", java.time.LocalDateTime.now().toString());
        if (!failed) {
            Map<Integer, ReferenceInfo> referenceMappings = generationReferenceMappings.get(generationId);
            if (referenceMappings != null && !referenceMappings.isEmpty()) {
                notification.put("referenceMappings", toSerializableReferenceMappings(referenceMappings));
            }
            Map<String, Object> diagnostics = generationDiagnostics.get(generationId);
            if (diagnostics != null && !diagnostics.isEmpty()) {
                notification.put("diagnostics", diagnostics);
            }
            List<Map<String, Object>> productStateItems = generationProductStateItems.get(generationId);
            if (productStateItems != null && !productStateItems.isEmpty()) {
                notification.put("productStateItems", productStateItems);
            }
        }
        if (persistenceDegraded) {
            notification.put("persistenceDegraded", true);
            notification.put("persistenceWarning", "本次回复未能持久化到数据库，刷新后可能无法在历史中找到。");
        }
        sendJsonToGenerationClient(userId, generationId, notification);
    }

    private void handleError(String userId, String generationId, Throwable error) {
        handleError(userId, null, generationId, error);
    }

    private void handleError(String userId, String clientId, String generationId, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        Map<String, Object> errorResponse = new HashMap<>();
        errorResponse.put("type", "error");
        errorResponse.put("generationId", generationId);
        RateLimitExceededException rateLimitExceededException = findRateLimitException(error);
        if (rateLimitExceededException != null) {
            errorResponse.put("code", 429);
            errorResponse.put("message", rateLimitExceededException.getMessage());
            errorResponse.put("retryAfterSeconds", rateLimitExceededException.getRetryAfterSeconds());
            sendJsonToGenerationOrClient(userId, clientId, generationId, errorResponse);
            return;
        }
        errorResponse.put("error", "AI服务暂时不可用，请稍后重试");
        sendJsonToGenerationOrClient(userId, clientId, generationId, errorResponse);
    }

    private RateLimitExceededException findRateLimitException(Throwable error) {
        Throwable current = error;
        while (current != null) {
            if (current instanceof RateLimitExceededException rateLimitExceededException) {
                return rateLimitExceededException;
            }
            current = current.getCause();
        }
        return null;
    }

    private void sendRateLimitMessage(String userId, String clientId, String generationId, RateLimitExceededException exception) {
        Map<String, Object> payload = new HashMap<>();
        payload.put("type", "error");
        payload.put("generationId", generationId);
        payload.put("code", 429);
        payload.put("message", exception.getMessage());
        payload.put("retryAfterSeconds", exception.getRetryAfterSeconds());
        sendJsonToGenerationOrClient(userId, clientId, generationId, payload);
    }

    private void sendJsonToGenerationOrClient(String userId,
                                              String clientId,
                                              String generationId,
                                              Map<String, ?> payload) {
        if (generationId != null && !generationId.isBlank() && generationClientIds.containsKey(generationId)) {
            sendJsonToGenerationClient(userId, generationId, payload);
            return;
        }
        sendJsonToClient(userId, clientId, payload);
    }

    private void sendJsonToGenerationClient(String userId, String generationId, Map<String, ?> payload) {
        String clientId = generationClientIds.get(generationId);
        if (clientId == null || clientId.isBlank()) {
            logger.debug("生成任务 {} 没有绑定 clientId，跳过 WebSocket 定向发送", generationId);
            return;
        }
        chatSessionRegistry.sendJsonToClient(userId, clientId, payload);
    }

    private void sendJsonToClient(String userId, String clientId, Map<String, ?> payload) {
        if (clientId == null || clientId.isBlank()) {
            logger.debug("用户 {} 的请求 clientId 为空，跳过 WebSocket 定向发送", userId);
            return;
        }
        chatSessionRegistry.sendJsonToClient(userId, clientId, payload);
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, String generationId) {
        stopResponse(userId, generationId, null);
    }

    public void stopResponse(String userId, String generationId, WebSocketSession requesterSession) {
        String requesterClientId = resolveClientId(requesterSession);
        String resolvedGenerationId = generationId;
        if (resolvedGenerationId == null || resolvedGenerationId.isBlank()) {
            if (requesterClientId != null && !requesterClientId.isBlank()) {
                resolvedGenerationId = chatGenerationStateService
                        .getActiveGenerationForUserAndClient(userId, requesterClientId)
                        .map(ChatGenerationStateService.GenerationSnapshot::generationId)
                        .orElse(null);
            } else {
                resolvedGenerationId = chatGenerationStateService.getActiveGenerationForUser(userId)
                        .map(ChatGenerationStateService.GenerationSnapshot::generationId)
                        .orElse(null);
            }
        }

        if (resolvedGenerationId == null || resolvedGenerationId.isBlank()) {
            logger.warn("收到停止请求但未找到活动生成任务，用户ID: {}", userId);
            return;
        }
        final String targetGenerationId = resolvedGenerationId;
        String targetClientId = generationClientIds.getOrDefault(targetGenerationId, requesterClientId);

        logger.info("收到停止请求，用户ID: {}，generationId: {}", userId, targetGenerationId);

        // 设置停止标志
        cancelledGenerations.add(targetGenerationId);
        stopFlags.put(targetGenerationId, true);
        chatGenerationStateService.markCancelled(targetGenerationId);
        CompletableFuture<String> responseFuture = responseFutures.get(targetGenerationId);
        if (responseFuture != null && !responseFuture.isDone()) {
            responseFuture.completeExceptionally(new CancellationException("响应已停止"));
        }

        sendJsonToClient(userId, targetClientId, Map.of(
                "type", "stop",
                "generationId", targetGenerationId,
                "message", "响应已停止",
                "timestamp", System.currentTimeMillis(),
                "date", java.time.Instant.now().toString()
        ));

        logger.info("已停止上游流式生成: generationId={}", targetGenerationId);
    }

    /**
     * 根据生成任务和引用编号获取论文标识
     *
     * @param generationId 生成任务ID
     * @param referenceNumber 引用编号
     * @return paperId，如果找不到则返回null
     */
    public String getReferencePaperId(String generationId, int referenceNumber) {
        ReferenceInfo detail = getReferenceDetail(generationId, referenceNumber);
        return detail != null ? detail.paperId() : null;
    }

    public ReferenceInfo getReferenceDetail(String generationId, int referenceNumber) {
        logger.info("查询引用证据: generationId={}, referenceNumber=#{}", generationId, referenceNumber);

        Map<Integer, ReferenceInfo> referenceMapping = generationReferenceMappings.get(generationId);
        if (referenceMapping == null) {
            referenceMapping = chatGenerationStateService.getGeneration(generationId)
                    .map(ChatGenerationStateService.GenerationSnapshot::referenceMappings)
                    .filter(mappings -> !mappings.isEmpty())
                    .map(this::toReferenceInfoMap)
                    .orElse(null);
        }
        if (referenceMapping == null) {
            logger.error("未找到生成任务 {} 的引用映射，当前所有生成任务: {}", generationId, generationReferenceMappings.keySet());
            return null;
        }

        logger.info("生成任务 {} 的引用映射内容: {}", generationId, referenceMapping);

        ReferenceInfo detail = referenceMapping.get(referenceNumber);
        if (detail == null) {
            logger.error("生成任务 {} 中未找到引用编号 #{}, 可用的引用编号: {}", generationId, referenceNumber, referenceMapping.keySet());
            return null;
        }

        logger.info("成功找到引用映射: generationId={}, referenceNumber=#{}, paperId={}, pageNumber={}",
                generationId, referenceNumber, detail.paperId(), detail.pageNumber());
        return detail;
    }

    private Map<Integer, ReferenceInfo> toReferenceInfoMap(Map<String, Map<String, Object>> serializedMappings) {
        Map<Integer, ReferenceInfo> referenceMap = new HashMap<>();
        for (Map.Entry<String, Map<String, Object>> entry : serializedMappings.entrySet()) {
            Map<String, Object> item = entry.getValue();
            referenceMap.put(Integer.parseInt(entry.getKey()), new ReferenceInfo(
                    (String) item.get("paperId"),
                    (String) item.get("paperTitle"),
                    (String) item.get("originalFilename"),
                    item.get("pageNumber") instanceof Number number ? number.intValue() : null,
                    (String) item.get("anchorText"),
                    (String) item.get("retrievalMode"),
                    (String) item.get("retrievalLabel"),
                    (String) item.get("retrievalQuery"),
                    (String) item.get("matchedChunkText"),
                    (String) item.get("evidenceSnippet"),
                    item.get("score") instanceof Number number ? number.doubleValue() : null,
                    item.get("chunkId") instanceof Number number ? number.intValue() : null,
                    (String) item.get("elementType"),
                    (String) item.get("sectionTitle"),
                    item.get("sectionLevel") instanceof Number number ? number.intValue() : null,
                    (String) item.get("bboxJson"),
                    (String) item.get("parserName"),
                    (String) item.get("parserVersion"),
                    (String) item.get("sourceKind"),
                    (String) item.get("tableId"),
                    (String) item.get("figureId"),
                    (String) item.get("formulaId"),
                    (String) item.get("evidenceRole"),
                    (String) item.get("retrievalRoute"),
                    (String) item.get("intent"),
                    (String) item.get("rankReason"),
                    (String) item.get("tableText"),
                    (String) item.get("tableMarkdown"),
                    item.get("tableScreenshotAvailable") instanceof Boolean value && value,
                    (String) item.get("sourceType"),
                    (String) item.get("evidenceAssetLevel"),
                    item.get("pdfEvidenceAvailable") instanceof Boolean value && value,
                    item.get("pageScreenshotAvailable") instanceof Boolean value && value,
                    item.get("figureScreenshotAvailable") instanceof Boolean value && value,
                    (String) item.get("citationRef"),
                    (String) item.get("evidenceRef"),
                    (String) item.get("sourceQuoteRef"),
                    stringListValue(item.get("assetWarnings"))
            ));
        }
        return referenceMap;
    }

    private List<String> stringListValue(Object raw) {
        if (!(raw instanceof List<?> rawList)) {
            return List.of();
        }
        return rawList.stream()
                .filter(value -> value != null && !String.valueOf(value).isBlank())
                .map(String::valueOf)
                .toList();
    }

    private String trimToMaxLength(String value, int maxLength) {
        String normalized = value == null ? "" : value.replaceAll("\\s+", " ").trim();
        if (normalized.length() <= maxLength) {
            return normalized;
        }
        return normalized.substring(0, maxLength) + "…";
    }

    private static final class ChatRequestTiming {
        private final long startedAtNanos = System.nanoTime();
        private final int userQueryLength;
        private final Map<String, Long> stageMs = new LinkedHashMap<>();
        private final Map<String, Long> activeStageStarts = new HashMap<>();
        private String route = "UNKNOWN";
        private int retrievalHitCount;
        private int citationCount;
        private long lastMarkNanos = startedAtNanos;

        private ChatRequestTiming(String userMessage) {
            this.userQueryLength = userMessage == null ? 0 : userMessage.length();
        }

        static ChatRequestTiming start(String userMessage) {
            return new ChatRequestTiming(userMessage);
        }

        void route(String route) {
            this.route = route;
        }

        void mark(String stage) {
            long now = System.nanoTime();
            stageMs.merge(stage, TimeUnit.NANOSECONDS.toMillis(now - lastMarkNanos), Long::sum);
            lastMarkNanos = now;
        }

        void begin(String stage) {
            activeStageStarts.put(stage, System.nanoTime());
        }

        void end(String stage) {
            Long stageStartedAt = activeStageStarts.remove(stage);
            if (stageStartedAt != null) {
                stageMs.merge(stage, TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - stageStartedAt), Long::sum);
            }
        }

        void retrievalHitCount(int retrievalHitCount) {
            this.retrievalHitCount = Math.max(this.retrievalHitCount, retrievalHitCount);
        }

        void citationCount(int citationCount) {
            this.citationCount = citationCount;
        }

        void log(Logger logger, String conversationId, String generationId) {
            logger.info(
                    "chat timing: conversationId={}, generationId={}, route={}, userQueryLength={}, retrievalHitCount={}, citationCount={}, totalMs={}, stageMs={}",
                    conversationId,
                    generationId,
                    route,
                    userQueryLength,
                    retrievalHitCount,
                    citationCount,
                    TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startedAtNanos),
                    stageMs
            );
        }
    }

    public record ReferenceInfo(
            String paperId,
            String paperTitle,
            String originalFilename,
            Integer pageNumber,
            String anchorText,
            String retrievalMode,
            String retrievalLabel,
            String retrievalQuery,
            String matchedChunkText,
            String evidenceSnippet,
            Double score,
            Integer chunkId,
            String elementType,
            String sectionTitle,
            Integer sectionLevel,
            String bboxJson,
            String parserName,
            String parserVersion,
            String sourceKind,
            String tableId,
            String figureId,
            String formulaId,
            String evidenceRole,
            String retrievalRoute,
            String intent,
            String rankReason,
            String tableText,
            String tableMarkdown,
            Boolean tableScreenshotAvailable,
            String sourceType,
            String evidenceAssetLevel,
            Boolean pdfEvidenceAvailable,
            Boolean pageScreenshotAvailable,
            Boolean figureScreenshotAvailable,
            String citationRef,
            String evidenceRef,
            String sourceQuoteRef,
            List<String> assetWarnings
    ) {
        public ReferenceInfo {
            sourceKind = sourceKind == null || sourceKind.isBlank() ? "TEXT" : sourceKind;
            evidenceRole = evidenceRole == null || evidenceRole.isBlank() ? "NORMAL_TEXT" : evidenceRole;
            tableScreenshotAvailable = Boolean.TRUE.equals(tableScreenshotAvailable);
            sourceType = "PDF";
            pdfEvidenceAvailable = Boolean.TRUE.equals(pdfEvidenceAvailable);
            pageScreenshotAvailable = Boolean.TRUE.equals(pageScreenshotAvailable);
            figureScreenshotAvailable = Boolean.TRUE.equals(figureScreenshotAvailable);
            citationRef = citationRef == null || citationRef.isBlank() ? null : citationRef.trim();
            evidenceRef = evidenceRef == null || evidenceRef.isBlank() ? null : evidenceRef.trim();
            sourceQuoteRef = sourceQuoteRef == null || sourceQuoteRef.isBlank() ? null : sourceQuoteRef.trim();
            evidenceAssetLevel = "PDF_VISUAL".equals(evidenceAssetLevel) || pdfEvidenceAvailable
                    ? "PDF_VISUAL"
                    : "PDF_PENDING_ASSETS";
            assetWarnings = assetWarnings == null ? List.of() : assetWarnings.stream()
                    .filter(value -> value != null && !value.isBlank())
                    .filter(value -> !isLegacyImportWarning(value))
                    .toList();
        }

        private static boolean isLegacyImportWarning(String value) {
            return value.startsWith("structured_") && value.endsWith("_text_only");
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String figureId,
                             String formulaId,
                             String evidenceRole,
                             String retrievalRoute,
                             String intent,
                             String rankReason,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable,
                             String sourceType,
                             String evidenceAssetLevel,
                             Boolean pdfEvidenceAvailable,
                             Boolean pageScreenshotAvailable,
                             Boolean figureScreenshotAvailable,
                             String citationRef,
                             String evidenceRef,
                             List<String> assetWarnings) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    figureId,
                    formulaId,
                    evidenceRole,
                    retrievalRoute,
                    intent,
                    rankReason,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    sourceType,
                    evidenceAssetLevel,
                    pdfEvidenceAvailable,
                    pageScreenshotAvailable,
                    figureScreenshotAvailable,
                    citationRef,
                    evidenceRef,
                    null,
                    assetWarnings
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String figureId,
                             String formulaId,
                             String evidenceRole,
                             String retrievalRoute,
                             String intent,
                             String rankReason,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    figureId,
                    formulaId,
                    evidenceRole,
                    retrievalRoute,
                    intent,
                    rankReason,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    null,
                    null,
                    false,
                    false,
                    false,
                    null,
                    null,
                    null,
                    List.of()
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    null,
                    null,
                    "NORMAL_TEXT",
                    null,
                    null,
                    null,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    null,
                    null,
                    false,
                    false,
                    false,
                    null,
                    null,
                    null,
                    List.of()
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion,
                             String sourceKind,
                             String tableId,
                             String tableText,
                             String tableMarkdown,
                             Boolean tableScreenshotAvailable,
                             String sourceType,
                             String evidenceAssetLevel,
                             Boolean pdfEvidenceAvailable,
                             Boolean pageScreenshotAvailable,
                             Boolean figureScreenshotAvailable,
                             List<String> assetWarnings) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    sourceKind,
                    tableId,
                    null,
                    null,
                    "NORMAL_TEXT",
                    null,
                    null,
                    null,
                    tableText,
                    tableMarkdown,
                    tableScreenshotAvailable,
                    sourceType,
                    evidenceAssetLevel,
                    pdfEvidenceAvailable,
                    pageScreenshotAvailable,
                    figureScreenshotAvailable,
                    null,
                    null,
                    null,
                    assetWarnings
            );
        }

        public ReferenceInfo(String paperId,
                             String paperTitle,
                             String originalFilename,
                             Integer pageNumber,
                             String anchorText,
                             String retrievalMode,
                             String retrievalLabel,
                             String retrievalQuery,
                             String matchedChunkText,
                             String evidenceSnippet,
                             Double score,
                             Integer chunkId,
                             String elementType,
                             String sectionTitle,
                             Integer sectionLevel,
                             String bboxJson,
                             String parserName,
                             String parserVersion) {
            this(
                    paperId,
                    paperTitle,
                    originalFilename,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    retrievalLabel,
                    retrievalQuery,
                    matchedChunkText,
                    evidenceSnippet,
                    score,
                    chunkId,
                    elementType,
                    sectionTitle,
                    sectionLevel,
                    bboxJson,
                    parserName,
                    parserVersion,
                    "TEXT",
                    null,
                    null,
                    null,
                    "NORMAL_TEXT",
                    null,
                    null,
                    null,
                    null,
                    null,
                    false,
                    null,
                    null,
                    false,
                    false,
                    false,
                    null,
                    null,
                    null,
                    List.of()
            );
        }
    }

    public record ChatRequest(
            String message,
            ProductReferenceFocus referenceFocus,
            RetrievalBudgetProfile retrievalBudgetProfile,
            String conversationId
    ) {
        public ChatRequest {
            retrievalBudgetProfile = retrievalBudgetProfile == null
                    ? RetrievalBudgetProfile.INTERACTIVE
                    : retrievalBudgetProfile;
            conversationId = conversationId == null || conversationId.isBlank() ? null : conversationId.trim();
        }

        public ChatRequest(String message, ProductReferenceFocus referenceFocus) {
            this(message, referenceFocus, RetrievalBudgetProfile.INTERACTIVE, null);
        }

        public ChatRequest(String message, ProductReferenceFocus referenceFocus, RetrievalBudgetProfile retrievalBudgetProfile) {
            this(message, referenceFocus, retrievalBudgetProfile, null);
        }

        public ChatRequest(String message, ProductReferenceFocus referenceFocus, String conversationId) {
            this(message, referenceFocus, RetrievalBudgetProfile.INTERACTIVE, conversationId);
        }
    }
}
