CREATE TABLE IF NOT EXISTS paper_passages (
    id BIGINT NOT NULL AUTO_INCREMENT,
    passage_ref VARCHAR(96) NOT NULL,
    paper_id VARCHAR(32) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    parent_section_id VARCHAR(96) DEFAULT NULL,
    parent_section_ref VARCHAR(96) DEFAULT NULL,
    section_title VARCHAR(500) DEFAULT NULL,
    page_number_from INT NOT NULL,
    page_number_to INT NOT NULL,
    reading_order_from INT NOT NULL,
    reading_order_to INT NOT NULL,
    document_ordinal INT NOT NULL,
    section_ordinal INT DEFAULT NULL,
    content_text LONGTEXT NOT NULL,
    index_text LONGTEXT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    estimated_token_count INT NOT NULL,
    source_span_json LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_paper_passages_ref (passage_ref),
    UNIQUE KEY uk_paper_passages_document_ordinal (paper_id, model_version, document_ordinal),
    INDEX idx_paper_passages_section_ordinal (paper_id, model_version, parent_section_id, section_ordinal),
    INDEX idx_paper_passages_section_order (paper_id, model_version, parent_section_id, reading_order_from),
    INDEX idx_paper_passages_page_range (paper_id, model_version, page_number_from, page_number_to)
);
