/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.blank$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'mdi:comment-question-outline',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'chat-history',
    path: '/chat-history',
    component: 'layout.base$view.chat-history',
    meta: {
      title: 'chat-history',
      i18nKey: 'route.chat-history',
      roles: ['ADMIN'],
      hideInMenu: true,
      icon: 'mdi:history',
      order: 2
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'invite-code',
    path: '/invite-code',
    component: 'layout.base$view.invite-code',
    meta: {
      title: 'invite-code',
      i18nKey: 'route.invite-code',
      icon: 'mdi:ticket-confirmation-outline',
      roles: ['ADMIN'],
      order: 6
    }
  },
  {
    name: 'knowledge-base',
    path: '/knowledge-base',
    component: 'layout.base$view.knowledge-base',
    meta: {
      title: 'knowledge-base',
      i18nKey: 'route.knowledge-base',
      icon: 'mdi:bookshelf',
      order: 3
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'model-provider',
    path: '/model-provider',
    component: 'layout.base$view.model-provider',
    meta: {
      title: 'model-provider',
      i18nKey: 'route.model-provider',
      icon: 'mdi:flask-outline',
      roles: ['ADMIN'],
      order: 5
    }
  },
  {
    name: 'org-tag',
    path: '/org-tag',
    component: 'layout.base$view.org-tag',
    meta: {
      title: 'org-tag',
      i18nKey: 'route.org-tag',
      icon: 'mdi:tag-multiple-outline',
      roles: ['ADMIN'],
      order: 4
    }
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      icon: 'mdi:account-circle-outline',
      order: 7
    }
  },
  {
    name: 'recharge',
    path: '/recharge',
    component: 'layout.base$view.recharge',
    meta: {
      title: 'recharge',
      i18nKey: 'route.recharge',
      icon: 'mdi:credit-card-outline',
      order: 8
    }
  },
  {
    name: 'recharge-manage',
    path: '/recharge-manage',
    component: 'layout.base$view.recharge-manage',
    meta: {
      title: 'recharge-manage',
      i18nKey: 'route.recharge-manage',
      icon: 'mdi:receipt-text-outline',
      roles: ['ADMIN'],
      order: 9
    }
  },
  {
    name: 'usage-monitor',
    path: '/usage-monitor',
    component: 'layout.base$view.usage-monitor',
    meta: {
      title: 'usage-monitor',
      i18nKey: 'route.usage-monitor',
      icon: 'mdi:chart-line',
      roles: ['ADMIN'],
      order: 6
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'mdi:account-group-outline',
      roles: ['ADMIN']
    }
  }
];
